import { useState } from 'react';
import { useSearchParams } from 'react-router';
import { Pagos } from './Pagos';
import { Card, Notice, Money, ErrorBox, FormModal, Modal, Fields, Documentos, GestionGate, useGestion, useGuardar, amount, str, opt, options, hoy, negocios, type Compra, type Catalogos, type Moneda, type Negocio, type Prestamo } from './shared';

export function Compras(){const[p]=useSearchParams();return <GestionGate><header className="g-header"><div><h1>Compras</h1><p>De lo que planeamos comprar a su pago y justificante.</p></div></header><ComprasPanel prestamoId={p.get('prestamo')||undefined}/></GestionGate>;}
export function ComprasPanel({prestamoId}:{prestamoId?:string}){
 const query=useGestion<{items:Compra[];mas?:boolean}>('compras'),cat=useGestion<Catalogos>('catalogos'),loans=useGestion<{items:Prestamo[]}>('prestamos');
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null),[state,setState]=useState('todos'),[negocio,setNegocio]=useState('todos'),[month,setMonth]=useState(''),[persona,setPersona]=useState(''),[group,setGroup]=useState('comprador'),[category,setCategory]=useState(''),[moneda,setMoneda]=useState<Moneda>('EUR');
 const all=query.data?.items||[];const rows=all.filter(c=>(!prestamoId||c.prestamo_id===prestamoId)&&c.moneda===moneda&&(state==='todos'||c.estado===state)&&(negocio==='todos'||c.negocio===negocio)&&(!month||(c.fecha_compra||c.fecha_prevista||'').startsWith(month))&&(!persona||c.comprador===persona)&&(!category||(c.categoria||'Sin categoría')===category));
 const realized=rows.filter(c=>c.estado==='comprada');const totals={previsto:rows.filter(c=>c.estado==='comprometida').reduce((s,c)=>s+c.estimado,0),comprado:realized.reduce((s,c)=>s+(c.real||0),0),pendiente:realized.reduce((s,c)=>s+c.pendiente,0)};
 const grouped=Object.entries(realized.reduce<Record<string,number>>((a,c)=>{const key=group==='mes'?(c.fecha_compra?.slice(0,7)||'Fecha pendiente'):group==='negocio'?negocios[c.negocio]:group==='categoria'?(c.categoria||'Sin categoría'):(c.comprador||'Comprador pendiente');a[key]=(a[key]||0)+(c.real||0);return a;},{})).sort((a,b)=>b[1]-a[1]);
 const max=Math.max(1,...grouped.map(r=>r[1]));const active=all.find(c=>c.id===selected);
 return <><div className="g-toolbar"><div><h2>Compras previstas y realizadas</h2><p className="muted">La previsión compromete presupuesto; el pago actualiza la caja.</p></div><button className="btn" onClick={()=>setCreating(true)}>Añadir compra</button></div><ErrorBox error={query.error||cat.error||loans.error}/><div className="g-filters"><label>Negocio<select value={negocio} onChange={e=>setNegocio(e.target.value)}><option value="todos">Todos</option>{Object.entries(negocios).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Estado<select value={state} onChange={e=>setState(e.target.value)}><option value="todos">Todos</option>{['prevista','comprometida','comprada','cancelada'].map(s=><option key={s}>{s}</option>)}</select></label><label>Mes<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Comprado por<select value={persona} onChange={e=>setPersona(e.target.value)}><option value="">Todas las personas</option>{[...new Set(all.map(c=>c.comprador).filter((v):v is string=>!!v))].map(n=><option key={n}>{n}</option>)}</select></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option>{[...new Set(all.map(c=>c.categoria||'Sin categoría'))].map(n=><option key={n}>{n}</option>)}</select></label><label>Moneda<select value={moneda} onChange={e=>setMoneda(e.target.value as Moneda)}><option>EUR</option><option>COP</option></select></label><button className="btn alt" onClick={()=>{setState('todos');setNegocio('todos');setMonth('');setPersona('');setCategory('');}}>Limpiar filtros</button></div>
 {query.data?.mas?<Notice>Se muestran las 500 compras más recientes. Estos filtros y gráficos corresponden a ese listado; consulta el resumen de fondos para los totales completos.</Notice>:null}<div className="g-metrics"><div><strong><Money value={totals.previsto} moneda={moneda}/></strong><span>comprometido sin comprar</span></div><div><strong><Money value={totals.comprado} moneda={moneda}/></strong><span>compras realizadas</span></div><div><strong><Money value={totals.pendiente} moneda={moneda}/></strong><span>pendiente de registrar pago</span></div></div>
 <Card title="Destino de las compras" action={<label>Agrupar por<select value={group} onChange={e=>setGroup(e.target.value)}><option value="comprador">Quién compró</option><option value="mes">Mes</option><option value="categoria">Categoría</option><option value="negocio">Negocio</option></select></label>}><div className="g-chart">{grouped.length?grouped.map(([name,total])=><div className="g-chart-row" key={name}><button className="g-chart-label" onClick={()=>{if(group==='comprador')setPersona(name);else if(group==='mes'&&/^\d{4}-\d{2}$/.test(name))setMonth(name);else if(group==='categoria')setCategory(name);else if(group==='negocio')setNegocio(Object.keys(negocios).find(k=>negocios[k as Negocio]===name)||'todos');}}>{name}</button><meter value={total} max={max} aria-label={`Compras: ${name}`}/><Money value={total} moneda={moneda}/></div>):<p className="g-empty">No hay compras realizadas con estos filtros.</p>}</div><p className="muted">Importes de compra, no reembolsos ni beneficio. Comprar y pagar con fondos propios son datos distintos.</p></Card>
 <Card title="Listado de compras">{query.isPending?<p role="status">Cargando compras…</p>:<div className="g-table"><table><thead><tr><th>Compra</th><th>Negocio / persona</th><th>Previsto</th><th>Real</th><th>Estado</th><th>Justificante</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><button className="g-row-button" onClick={()=>setSelected(c.id)}>{c.concepto}</button><small>{c.fecha_compra||c.fecha_prevista||'Fecha pendiente'}</small></td><td>{negocios[c.negocio]}<small>{c.comprador||'Por asignar'}</small></td><td><Money value={c.estimado} moneda={c.moneda}/></td><td><Money value={c.real} moneda={c.moneda}/></td><td><span className={`g-badge ${c.estado==='comprada'?'done':''}`}>{c.estado}</span>{c.estado==='comprada'?<small>{c.pendiente>0?'Pago sin registrar o parcial':'Pagada'}</small>:null}</td><td>{c.documentos_count?<span>Adjunto</span>:<span className="g-badge">Pendiente</span>}</td></tr>)}</tbody></table>{!rows.length?<p className="g-empty">Añade una compra para organizar su presupuesto y quién se encargará.</p>:null}</div>}</Card>
 {creating?<PurchaseForm close={()=>setCreating(false)} cat={cat.data} loans={loans.data?.items||[]} prestamoId={prestamoId}/>:null}{active?<PurchaseDetail item={active} cat={cat.data} close={()=>setSelected(null)}/>:null}</>;
}
function PurchaseForm({close,cat,loans,prestamoId}:{close:()=>void;cat?:Catalogos;loans:Prestamo[];prestamoId?:string}){
 const save=useGuardar();return <FormModal title="Añadir compra prevista" close={close} fields={[{name:'concepto',label:'Qué vamos a comprar',required:true},{name:'negocio',label:'Negocio',options:Object.entries(negocios).map(([value,label])=>({value,label}))},{name:'estimado',label:'Importe previsto',required:true},{name:'moneda',label:'Moneda',options:[{value:'EUR',label:'EUR'},{value:'COP',label:'COP'}]},{name:'entidad_id',label:'Entidad',options:options(cat?.entidades||[],'Pendiente de asignar')},{name:'prestamo_id',label:'Origen de fondos',value:prestamoId,options:options(loans,'Sin préstamo asignado')},{name:'comprador',label:'Quién se encargará'},{name:'categoria',label:'Categoría',value:'Equipamiento'},{name:'fecha_prevista',label:'Fecha prevista',type:'date'},{name:'estado',label:'Presupuesto',options:[{value:'prevista',label:'Idea o compra prevista'},{value:'comprometida',label:'Reservar presupuesto para esta compra'}]},{name:'nota',label:'Notas',type:'textarea'}]} submit={(d,id)=>save.mutateAsync({path:'compras',body:{id,concepto:str(d,'concepto'),negocio:str(d,'negocio'),estimado:amount(d,'estimado',str(d,'moneda') as Moneda),moneda:str(d,'moneda'),entidad_id:opt(d,'entidad_id'),prestamo_id:opt(d,'prestamo_id'),comprador:opt(d,'comprador'),categoria:str(d,'categoria'),fecha_prevista:opt(d,'fecha_prevista'),estado:str(d,'estado'),nota:opt(d,'nota')}})}><Notice>Esta previsión no mueve dinero ni registra un gasto pagado. Después podrás marcar «Se compró» e indicar el valor real.</Notice></FormModal>;
}
function PurchaseDetail({item,cat,close}:{item:Compra;cat?:Catalogos;close:()=>void}){
 const [action,setAction]=useState<'comprar'|'pagar'|'editar'|'cancelar'|null>(null),save=useGuardar();
 return <Modal title={item.concepto} close={close}><div className="g-metrics"><div><strong><Money value={item.real??item.estimado} moneda={item.moneda}/></strong><span>{item.real==null?'estimado':'importe real'}</span></div><div><strong><Money value={item.pagado} moneda={item.moneda}/></strong><span>pagado al proveedor</span></div><div><strong><Money value={item.pendiente} moneda={item.moneda}/></strong><span>pendiente</span></div></div><dl className="g-definition"><div><dt>Negocio</dt><dd>{negocios[item.negocio]}</dd></div><div><dt>Comprado por</dt><dd>{item.comprador||'Por asignar'}</dd></div><div><dt>Proveedor</dt><dd>{item.proveedor||'Por confirmar'}</dd></div><div><dt>Fecha de compra</dt><dd>{item.fecha_compra?.split('-').reverse().join('/')||'Por confirmar'}</dd></div><div><dt>Estado</dt><dd>{item.estado}</dd></div><div><dt>Notas</dt><dd>{item.nota||'Sin notas'}</dd></div></dl><div className="g-inline">{['prevista','comprometida'].includes(item.estado)?<button className="btn" onClick={()=>setAction('comprar')}>Se compró</button>:null}{item.estado==='comprada'&&item.pendiente>0?<button className="btn" onClick={()=>setAction('pagar')}>Registrar pago</button>:null}<button className="btn alt" onClick={()=>setAction('editar')}>Editar datos</button>{['prevista','comprometida'].includes(item.estado)?<button className="btn alt" onClick={()=>setAction('cancelar')}>Cancelar compra</button>:null}</div><Pagos tipo="compra" objetoId={item.id}/><Documentos tipo="compra" objetoId={item.id}/>
 {action==='comprar'?<FormModal title="Confirmar compra realizada" close={()=>setAction(null)} label="Confirmar compra" fields={[{name:'real',label:`Importe real (${item.moneda})`,value:item.estimado/(item.moneda==='EUR'?100:1),required:true},{name:'fecha',label:'Fecha de compra (si está confirmada)',type:'date',help:'Puedes completarla después con el justificante.'},{name:'comprador',label:'Quién compró',value:item.comprador,required:true},{name:'proveedor',label:'Proveedor',value:item.proveedor,required:true}]} submit={d=>save.mutateAsync({path:`compras/${item.id}/comprar`,body:{version:item.version,real:amount(d,'real',item.moneda),fecha:opt(d,'fecha'),comprador:str(d,'comprador'),proveedor:str(d,'proveedor')}})}><Notice>Podrás registrar el pago y adjuntar la factura después. El valor real sustituye la previsión, sin descontarlos dos veces.</Notice></FormModal>:action==='pagar'?<PurchasePayment item={item} cat={cat} close={()=>setAction(null)}/>:action==='editar'?<FormModal title="Editar datos de la compra" close={()=>setAction(null)} fields={[{name:'concepto',label:'Concepto',value:item.concepto,required:true},{name:'comprador',label:'Quién compra',value:item.comprador},{name:'categoria',label:'Categoría',value:item.categoria},{name:'proveedor',label:'Proveedor',value:item.proveedor},...(item.estado==='comprada'?[{name:'fecha_compra',label:'Fecha de compra confirmada',type:'date',value:item.fecha_compra}]:[]),{name:'nota',label:'Notas',type:'textarea',value:item.nota}]} submit={d=>save.mutateAsync({path:`compras/${item.id}`,method:'PATCH',body:{version:item.version,concepto:str(d,'concepto'),comprador:opt(d,'comprador'),categoria:str(d,'categoria'),proveedor:opt(d,'proveedor'),...(item.estado==='comprada'?{fecha_compra:opt(d,'fecha_compra')} : {}),nota:opt(d,'nota')}})}/>:action==='cancelar'?<FormModal title="Cancelar compra prevista" close={()=>setAction(null)} label="Cancelar y liberar presupuesto" fields={[{name:'nota',label:'Motivo de cancelación',required:true,type:'textarea'}]} submit={d=>save.mutateAsync({path:`compras/${item.id}`,method:'PATCH',body:{version:item.version,estado:'cancelada',nota:str(d,'nota')}})}><Notice>Se conserva el registro y se libera el compromiso de presupuesto. Esta acción no devuelve un pago ya realizado.</Notice></FormModal>:null}
 </Modal>;
}
function PurchasePayment({item,cat,close}:{item:Compra;cat?:Catalogos;close:()=>void}){
 const [payer,setPayer]=useState('cuenta'),save=useGuardar();
 return <FormModal title="Registrar pago de la compra" close={close} fields={[{name:'fecha',label:'Fecha del pago',type:'date',value:hoy(),required:true},{name:'importe',label:`Importe pagado (${item.moneda})`,value:item.pendiente/(item.moneda==='EUR'?100:1),required:true},{name:'nota',label:'Referencia del pago'}]} submit={(d,id)=>save.mutateAsync({path:`compras/${item.id}/pagos`,body:{id,fecha:str(d,'fecha'),importe:amount(d,'importe',item.moneda),pagador:payer,cuenta_id:payer==='cuenta'?str(d,'cuenta_id'):null,socio:payer==='socio'?str(d,'socio'):null,nota:opt(d,'nota')}})}><label className="g-full-label">Origen del dinero<select value={payer} onChange={e=>setPayer(e.target.value)}><option value="cuenta">Cuenta del proyecto</option><option value="socio">Fondos personales de un socio</option></select></label>{payer==='cuenta'?<Fields fields={[{name:'cuenta_id',label:'Cuenta desde la que se pagó',options:options((cat?.cuentas||[]).filter(c=>c.moneda===item.moneda)),required:true}]}/>:<Fields fields={[{name:'socio',label:'Quién adelantó su dinero',options:[{value:'',label:'Seleccionar socio'},...(cat?.socios||[]).map(s=>({value:s.email,label:s.nombre}))],required:true}]}/>}<Notice>{payer==='cuenta'?'Aunque Juan u otra persona haga la compra, pagar con la cuenta común no genera una deuda con ese socio.':'El adelanto queda pendiente de devolver al socio. No se descuenta de la cuenta común hasta que se reembolse.'}</Notice></FormModal>;
}
