import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { Card, Notice, Money, ErrorBox, FormModal, Documentos, EntityOptions, GestionGate, useGestion, useGuardar, amount, str, opt, options, hoy, type Catalogos, type Prestamo, type ResumenPrestamo, type Cuota, type Field } from './shared';
import { ComprasPanel } from './Compras';
import { Fondos } from './Fondos';
import { Pagos } from './Pagos';

export function Credito(){return <GestionGate><CreditoPanel/></GestionGate>;}
function CreditoPanel(){
 const loans=useGestion<{items:Prestamo[]}>('prestamos'),cat=useGestion<Catalogos>('catalogos');
 const [params,setParams]=useSearchParams(),[create,setCreate]=useState(false);
 const current=loans.data?.items.find(p=>p.id===params.get('prestamo'))||loans.data?.items[0];
 const detail=useGestion<ResumenPrestamo>(`prestamos/${current?.id}/resumen`,!!current);
 const tab=['amortizacion','destino','documentos'].includes(params.get('vista')||'')?params.get('vista')!:'resumen';
 const [action,setAction]=useState<'condiciones'|'desembolso'|Cuota|null>(null);
 function change(k:string,v:string){setParams(old=>{const next=new URLSearchParams(old);next.set(k,v);return next;});}
 return <><header className="g-header"><div><h1>Crédito y fondos</h1><p>{current?`${current.nombre} · EUR`:'Contratos, cuotas y destino del dinero del proyecto.'}</p></div><div className="g-inline">{(loans.data?.items.length||0)>1?<label>Préstamo<select value={current?.id} onChange={e=>change('prestamo',e.target.value)}>{loans.data?.items.map(p=><option value={p.id} key={p.id}>{p.nombre}</option>)}</select></label>:null}<button className="btn alt" onClick={()=>setCreate(true)}>Añadir préstamo</button></div></header>
 <ErrorBox error={loans.error||detail.error||cat.error}/>
 {loans.isPending?<p role="status">Cargando préstamos…</p>:!current?<Card title="El expediente empieza aquí"><p>Añade las condiciones de tu préstamo y sus documentos. El alta no registra ingresos ni marca cuotas como pagadas.</p><div className="g-inline"><EntityOptions onDone={()=>{}}/><button className="btn" onClick={()=>setCreate(true)}>Crear expediente</button></div></Card>:<>
 <nav className="g-tabs" aria-label="Vistas del crédito">{[['resumen','Resumen'],['amortizacion','Amortización'],['destino','Destino del dinero'],['documentos','Documentos']].map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>change('vista',key!)}>{label}</button>)}</nav>
 {tab==='destino'?<><Fondos/><ComprasPanel prestamoId={current.id}/></>:tab==='documentos'?<Documentos tipo="prestamo" objetoId={current.id}/>:tab==='amortizacion'?<><Amortizacion data={detail.data} pay={q=>setAction(q)}/><Pagos tipo="prestamo" objetoId={current.id}/></>:<>
 <div className="g-metrics"><div><strong><Money value={current.principal}/></strong><span>Capital contratado</span></div><div><strong><Money value={current.cuota}/></strong><span>Cuota mensual</span></div><div><strong>{current.meses}</strong><span>meses</span></div><div><strong className="g-rate">TIN {(current.tin_bp/100).toLocaleString('es-ES')} %</strong><span>TAE {(current.tae_bp/100).toLocaleString('es-ES')} %</span></div><button className="btn" onClick={()=>setAction('condiciones')}>Ver condiciones</button></div>
 <div className="g-credit-grid"><Card title="Condiciones del contrato"><dl className="g-definition"><div><dt>Capital contratado</dt><dd><Money value={current.principal}/></dd></div><div><dt>Comisión de apertura</dt><dd><Money value={current.apertura}/></dd></div><div><dt>Total proyectado con apertura</dt><dd><Money value={detail.data?detail.data.calendario.reduce((s,q)=>s+q.cuota,0)+current.apertura:null}/></dd></div><div><dt>Primer vencimiento</dt><dd>{current.primer_vencimiento?.split('-').reverse().join('/')||'Por confirmar'}</dd></div></dl><Notice>{detail.data?.desembolsado?'Desembolso registrado. La conciliación se contrasta con el extracto de la cuenta.':'Saldo real pendiente de conciliación. Confirma el abono y la apertura con el extracto.'}</Notice>{!detail.data?.desembolsado?<button className="btn alt" onClick={()=>setAction('desembolso')}>Registrar abono del préstamo</button>:null}</Card>
 <Card title="Reserva inicial" className="g-reserve"><h3>{current.reserva_cuotas} cuotas {detail.data?.desembolsado?'reservadas':'previstas para reservar'}</h3><strong className="g-reserve-amount"><Money value={detail.data?.desembolsado?detail.data.reserva_restante:current.cuota*current.reserva_cuotas}/></strong><p>{detail.data?.desembolsado?'Fondos apartados para los cobros mensuales.':'Reserva prevista. Se activará al confirmar el abono del préstamo.'}</p><b>Reservar no significa pagar.</b><ol className="g-reserve-steps" aria-label="Estado de las cuotas reservadas">{Array.from({length:Math.min(current.reserva_cuotas,12)},(_,i)=>{const q=detail.data?.calendario[i];return <li key={i} data-paid={q&&q.pagado>=q.cuota?'true':'false'}><span>{i+1}</span><small>Cuota {i+1}</small><Money value={q?.cuota??current.cuota}/><small>{q&&q.pagado>=q.cuota?'Pagada':q?.pagado?'Pago parcial':detail.data?.desembolsado?'Reservada':'Por reservar'}</small></li>;})}</ol></Card></div>
 <div className="g-section-link"><Link to={`/compras?prestamo=${current.id}`}>Ver compras y destino del dinero</Link></div><Documentos tipo="prestamo" objetoId={current.id}/>
 </>}
 </>}
 {create?<LoanForm close={()=>setCreate(false)} catalogos={cat.data} saved={id=>{change('prestamo',id);setCreate(false);}}/>:null}
 {current&&action==='condiciones'?<Conditions loan={current} close={()=>setAction(null)}/>:current&&action==='desembolso'?<Disbursement loan={current} close={()=>setAction(null)}/>:current&&typeof action==='object'&&action?<Payment loan={current} cuota={action} close={()=>setAction(null)}/>:null}
 </>;
}
function LoanForm({close,catalogos,saved}:{close:()=>void;catalogos?:Catalogos;saved:(id:string)=>void}){
 const save=useGuardar();const [conditions,setConditions]=useState<{concepto:string;valor:string;fuente:string}[]>([]);
 const fields:Field[]=[{name:'nombre',label:'Nombre del préstamo',required:true},{name:'cuenta_id',label:'Cuenta donde se recibe',options:options((catalogos?.cuentas||[]).filter(c=>c.moneda==='EUR')),required:true},{name:'principal',label:'Capital contratado (€)',required:true},{name:'apertura',label:'Comisión de apertura (€)',required:true,value:'0'},{name:'cuota',label:'Cuota mensual (€)',required:true},{name:'meses',label:'Número de mensualidades',type:'number',min:'1',max:'600',required:true},{name:'tin',label:'TIN anual (%)',type:'number',min:'0',max:'100',step:'.01',required:true},{name:'tae',label:'TAE informativa (%)',type:'number',min:'0',max:'100',step:'.01',required:true},{name:'reserva_cuotas',label:'Cuotas que se reservan',type:'number',min:'0',max:'120',value:'6'},{name:'primer_vencimiento',label:'Primer vencimiento (si está confirmado)',type:'date'}];
 return <FormModal title="Crear expediente del préstamo" close={close} fields={fields} submit={async(d,id)=>{await save.mutateAsync({path:'prestamos',body:{id,nombre:str(d,'nombre'),cuenta_id:str(d,'cuenta_id'),principal:amount(d,'principal'),apertura:amount(d,'apertura'),cuota:amount(d,'cuota'),meses:Number(str(d,'meses')),tin_bp:Math.round(Number(str(d,'tin'))*100),tae_bp:Math.round(Number(str(d,'tae'))*100),reserva_cuotas:Number(str(d,'reserva_cuotas')),primer_vencimiento:opt(d,'primer_vencimiento'),condiciones:conditions.filter(c=>c.concepto&&c.valor)}});saved(id);}}><h3>Otras condiciones documentadas</h3>{conditions.map((c,i)=><div className="g-condition-input" key={i}>{(['concepto','valor','fuente'] as const).map(k=><label key={k}>{k==='concepto'?'Condición':k==='valor'?'Valor o descripción':'Página de origen'}<input value={c[k]} maxLength={k==='concepto'?120:k==='valor'?300:200} required={k!=='fuente'&&!!(c.concepto||c.valor)} onChange={e=>setConditions(cs=>cs.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/></label>)}</div>)}<button type="button" className="btn alt" onClick={()=>setConditions(c=>[...c,{concepto:'',valor:'',fuente:''}])}>Añadir condición</button><Notice>Las fechas desconocidas quedan pendientes. El cuadro inicial es una proyección; se contrastará con el cuadro bancario.</Notice>{!catalogos?.cuentas.length?<EntityOptions onDone={()=>{}}/>:null}</FormModal>;
}
function Conditions({loan,close}:{loan:Prestamo;close:()=>void}){
 const save=useGuardar();const [conditions,setConditions]=useState(loan.condiciones.map(c=>({...c,fuente:c.fuente||''})));
 return <FormModal title="Condiciones y fechas" close={close} fields={[{name:'primer_vencimiento',label:'Primer vencimiento confirmado por el banco',type:'date',value:loan.primer_vencimiento},{name:'reserva_cuotas',label:'Cuotas a reservar',type:'number',min:'0',max:String(loan.meses),value:loan.reserva_cuotas}]} submit={d=>save.mutateAsync({path:`prestamos/${loan.id}`,method:'PATCH',body:{version:loan.version,primer_vencimiento:opt(d,'primer_vencimiento'),reserva_cuotas:Number(str(d,'reserva_cuotas')),condiciones:conditions.filter(c=>c.concepto||c.valor)}})}>
 <h3>Condiciones documentadas</h3>{conditions.map((c,i)=><div className="g-condition-input" key={i}>{(['concepto','valor','fuente'] as const).map(k=><label key={k}>{k==='concepto'?'Condición':k==='valor'?'Valor o descripción':'Página de origen'}<input value={c[k]} maxLength={k==='concepto'?120:k==='valor'?300:200} required={k!=='fuente'&&!!(c.concepto||c.valor)} onChange={e=>setConditions(cs=>cs.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/></label>)}</div>)}<button type="button" className="btn alt" disabled={conditions.length>=50} onClick={()=>setConditions(c=>[...c,{concepto:'',valor:'',fuente:''}])}>Añadir condición</button>
 <Notice>Puedes completar los datos pendientes y adjuntar los documentos desde el expediente. Si cambia el contrato, conserva la liquidación y el cuadro actualizado del banco.</Notice></FormModal>;
}
function Disbursement({loan,close}:{loan:Prestamo;close:()=>void}){const save=useGuardar();return <FormModal title="Registrar el abono real" close={close} fields={[{name:'fecha',label:'Fecha del abono según extracto',type:'date',required:true},{name:'importe',label:'Capital recibido (€)',value:String(loan.principal/100),required:true},{name:'apertura',label:'Cargo de apertura (€)',value:String(loan.apertura/100),required:true}]} submit={(d,id)=>save.mutateAsync({path:`prestamos/${loan.id}/desembolso`,body:{id,fecha:str(d,'fecha'),importe:amount(d,'importe'),apertura:amount(d,'apertura')}})}><Notice>Se registran el abono y la apertura una sola vez. Comprueba que no estén ya incluidos en el saldo inicial de la cuenta.</Notice></FormModal>;}
function Payment({loan,cuota,close}:{loan:Prestamo;cuota:Cuota;close:()=>void}){const save=useGuardar();return <FormModal title={`Registrar pago · cuota ${cuota.numero}`} close={close} fields={[{name:'fecha',label:'Fecha del cargo',type:'date',required:true,value:hoy()},{name:'importe',label:'Importe total pagado (€)',value:(cuota.cuota-cuota.pagado)/100,required:true},{name:'capital',label:'Capital amortizado (€)',required:true},{name:'interes',label:'Interés cobrado (€)',required:true},{name:'comision',label:'Otros cargos (€)',value:'0',required:true},{name:'nota',label:'Referencia bancaria o nota'}]} submit={(d,id)=>save.mutateAsync({path:`prestamos/${loan.id}/pagos`,body:{id,numero:cuota.numero,fecha:str(d,'fecha'),importe:amount(d,'importe'),capital:amount(d,'capital'),interes:amount(d,'interes'),comision:amount(d,'comision'),nota:opt(d,'nota')}})}><Notice>Revisa el desglose del banco. Previsión de esta cuota: capital <Money value={cuota.capital}/> e interés <Money value={cuota.interes}/>. Solo se reducirá la deuda por el capital efectivamente pagado.</Notice></FormModal>;}
function Amortizacion({data,pay}:{data?:ResumenPrestamo;pay:(q:Cuota)=>void}){
 const [year,setYear]=useState('todo');if(!data)return <p role="status">Preparando calendario…</p>;
 const rows=data.calendario.filter(q=>year==='todo'||Math.ceil(q.numero/12)===Number(year));
 return <><div className="g-metrics"><div><strong>{data.calendario.filter(q=>q.estado==='pagada').length} / {data.prestamo.meses}</strong><span>cuotas pagadas</span></div><div><strong><Money value={data.desembolsado?data.principal_pendiente:null}/></strong><span>principal pendiente registrado</span></div><div><strong><Money value={data.reserva_restante}/></strong><span>reserva restante</span></div></div><Card title="Evolución del capital"><p>Proyección del principal pendiente al final de cada año.</p><div className="g-chart">{data.calendario.filter(q=>q.numero%12===0||q.numero===data.prestamo.meses).map(q=><div className="g-chart-row" key={q.numero}><span>Mes {q.numero}</span><meter min="0" max={data.prestamo.principal} value={q.saldo} aria-label={`Principal previsto mes ${q.numero}`}/><Money value={q.saldo}/></div>)}</div><Notice>Es una proyección con períodos mensuales regulares. Fechas hábiles y cuota final se contrastan con el calendario del banco.</Notice></Card><Card title="Calendario mensual" action={<label>Año del préstamo<select value={year} onChange={e=>setYear(e.target.value)}><option value="todo">Todos</option>{Array.from({length:Math.ceil(data.prestamo.meses/12)},(_,i)=><option key={i} value={i+1}>Año {i+1}</option>)}</select></label>}><div className="g-table"><table><thead><tr><th>Cuota</th><th>Vencimiento previsto</th><th>Cuota</th><th>Interés</th><th>Capital</th><th>Saldo previsto</th><th>Pagado</th><th>Acción</th></tr></thead><tbody>{rows.map(q=><tr key={q.numero}><td>{q.numero}</td><td>{q.fecha?.split('-').reverse().join('/')||'Por confirmar'}</td><td><Money value={q.cuota}/></td><td><Money value={q.interes}/></td><td><Money value={q.capital}/></td><td><Money value={q.saldo}/></td><td><Money value={q.pagado}/><small>{q.estado}</small></td><td><button className="btn alt btnsm" disabled={!data.desembolsado||q.pagado>=q.cuota} onClick={()=>pay(q)}>Registrar pago</button></td></tr>)}</tbody></table></div></Card></>;
}
