import { useState, type FormEvent } from 'react';
import { useInfiniteQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router';
import { api } from '../../api/client';
import { Card, Documentos, EntityOptions, Fields, FormModal, GestionGate, Modal, Money, Notice, negocios, opt, str, useGestion, useGuardar, type Catalogos, type Compra, type Entidad, type Moneda, type Negocio } from './shared';
import './fiscal.css';

type Tratamiento = 'pendiente' | 'general' | 'exento' | 'no_sujeto' | 'inversion' | 'rebu';
type EstadoFactura = 'borrador' | 'registrada' | 'validada';
export interface LineaFactura { descripcion:string; cantidad:string; precio_unitario:number; descuento:number; iva_bp:number|null; retencion_bp:number; base:number; iva:number; retencion:number; total:number }
export interface Factura {
 id:string; entidad_id:string; moneda:Moneda; negocio:Negocio; tipo:'recibida'|'emitida'; estado:EstadoFactura; origen:'borrador'|'externa'; clase:'ordinaria'|'rectificativa'; tratamiento_fiscal:Tratamiento;
 contraparte_nombre:string|null; contraparte_nif:string|null; contraparte_direccion:string|null; numero:string|null; fecha_emision:string|null; fecha_operacion:string|null; fecha_recepcion:string|null;
 compra_id:string|null; proveedor_emision:string|null; nota:string|null; nota_fiscal:string|null; rectifica_id:string|null; correccion_de:string|null; motivo_correccion:string|null;
 base:number; iva:number; retencion:number; total:number; iva_deducible:number; lineas:LineaFactura[]; documentos_count:number; originales_count:number; version:number; revision:string|null;
 snapshot:{entidad:{nombre:string;nif:string;direccion:string};revisada_por:string;revisada_en:string}|null;
}
export const tratamientoLabels:Record<Tratamiento,string>={pendiente:'Pendiente de clasificar',general:'Régimen general',exento:'Exenta',no_sujeto:'No sujeta',inversion:'Inversión del sujeto pasivo',rebu:'REBU · bienes usados'};
const estadoLabels:Record<EstadoFactura,string>={borrador:'Borrador',registrada:'Pendiente de revisión',validada:'Validada'};
export const incidenciaLabels:Record<string,string>={pendiente_revision:'Revisión pendiente',borrador_sin_valor_fiscal:'Borrador sin valor fiscal',tratamiento_fiscal_pendiente:'Tratamiento fiscal pendiente',regimen_requiere_asesoria:'Régimen que requiere asesoría',original_pendiente:'Falta adjuntar el original',fecha_pendiente:'Fecha pendiente',revision_sustituida:'Revisión sustituida'};
const errores:Record<string,string>={
 entidad_fiscal_incompleta:'Completa y verifica la razón social, el NIF y el domicilio de Velai antes de validar o cerrar un período.',
 original_externo_incompleto:'Faltan datos del original: número, fechas o identificación completa del cliente o proveedor.',original_pendiente:'Adjunta el documento original antes de validar.',
 tratamiento_fiscal_pendiente:'Selecciona el tratamiento fiscal después de revisar el original.',tipo_iva_pendiente:'Indica el IVA de cada línea; pendiente no equivale a cero.',
 fundamento_fiscal_pendiente:'Revisa la cuota y documenta el fundamento de la exención o no sujeción.',regimen_requiere_asesoria:'Este régimen requiere revisión de asesoría y todavía no puede incorporarse al cálculo fiscal.',
 version_desactualizada:'Otra persona actualizó el registro. Tus cambios siguen aquí; cierra el formulario y revisa la versión actual antes de reintentar.',
 factura_externa_duplicada:'Esta factura ya está registrada para el mismo emisor, número y año. Busca el registro existente.',correccion_ya_existe:'Ya existe una corrección de este registro. Continúa desde esa revisión.',
 factura_inmutable:'La factura validada conserva su original. Prepara una corrección interna para registrar un cambio.',periodo_cerrado:'El período está cerrado. Reábrelo con un motivo antes de modificar sus registros.',
 cierre_desactualizado:'El libro cambió mientras se preparaba el cierre. Actualiza el resumen y vuelve a revisarlo.',periodo_ya_cerrado:'El rango coincide con un período cerrado. Consulta su historial o cambia las fechas.',
 cierre_con_pendientes:'Revisa las incidencias o confirma expresamente que se conservarán como pendientes.',periodo_invalido:'La fecha final debe ser igual o posterior a la inicial.',periodo_demasiado_amplio:'Divide la consulta en períodos de hasta 367 días.',
 demasiadas_facturas_dividir_periodo:'Este período contiene demasiados registros. Usa un rango de fechas más corto.',demasiadas_lineas_dividir_periodo:'Hay demasiadas líneas para una sola exportación. Divide las fechas.',snapshot_grande_dividir_periodo:'Divide el período para conservar un cierre completo.',
 network_failed:'No pudimos conectar. Tus datos siguen aquí; puedes reintentar.',session_expired:'La sesión caducó. Vuelve a iniciar sesión para continuar.',not_authorized:'Tu cuenta no tiene permiso para consultar esta sección.',
 importe_invalido:'Revisa los importes: usa números sin separador de miles y hasta dos decimales en EUR.',cantidad_invalida:'La cantidad debe ser positiva y tener hasta cuatro decimales.',tipo_iva_invalido:'El porcentaje debe estar entre 0 y 100, con hasta dos decimales.',lineas_invalidas:'Añade entre una y cien líneas con descripción e importe.',motivo_insuficiente:'Describe el motivo con al menos cinco caracteres.',
};
export function FiscalError({error}:{error:unknown}) { if(!error)return null;const code=error instanceof Error?error.message:String(error);return <p role="alert" className="g-error">{errores[code]||`No se pudo guardar o cargar la información. ${code}`}</p>; }
export function entidadCompleta(e:Entidad|undefined) {return !!e&&e.tipo!=='promotores'&&e.estado==='activa'&&!!e.nif?.trim()&&!!e.direccion?.trim();}
export function minorInput(n:number,moneda:Moneda) {return moneda==='COP'?String(n):(n/100).toFixed(2);}
export function parseMinor(raw:string,moneda:Moneda,negative=false) {
 const normalized=raw.trim().replace(',','.');
 if(!(moneda==='EUR'?/^-?\d+(?:\.\d{1,2})?$/:/^-?\d+$/).test(normalized))throw new Error('importe_invalido');
 const sign=normalized.startsWith('-')?-1n:1n;const [whole='0',decimal='']=normalized.replace('-','').split('.');
 const value=sign*(BigInt(whole)*(moneda==='EUR'?100n:1n)+(moneda==='EUR'?BigInt(decimal.padEnd(2,'0')):0n));
 if(value>1000000000000n||value< -1000000000000n||(!negative&&value<0n))throw new Error('importe_invalido');return Number(value);
}
function parseRate(raw:string,nullable=false) {if(!raw.trim()&&nullable)return null;const n=parseMinor(raw||'0','EUR');if(n>10000)throw new Error('tipo_iva_invalido');return n;}
function useFacturas(path:string,enabled=true) {return useInfiniteQuery({queryKey:['gestion',path],initialPageParam:'',enabled,queryFn:({pageParam})=>api<{items:Factura[];nextCursor:string|null}>(`/api/admin/gestion/${path}${pageParam?`&cursor=${encodeURIComponent(pageParam)}`:''}`),getNextPageParam:last=>last.nextCursor||undefined});}

export function Facturacion(){return <GestionGate><FacturacionContent/></GestionGate>;}
function FacturacionContent(){
 const cat=useGestion<Catalogos>('catalogos');const [params,setParams]=useSearchParams();
 const [entidad,setEntidad]=useState(''),[moneda,setMoneda]=useState<Moneda>('EUR'),[tipo,setTipo]=useState(''),[estado,setEstado]=useState('');
 const [editor,setEditor]=useState<'borrador'|'externa'|null>(null);
 const entityId=entidad||cat.data?.entidades[0]?.id||'';const issuer=cat.data?.entidades.find(e=>e.id===entityId);
 const query=new URLSearchParams({entidad_id:entityId,moneda});if(tipo)query.set('tipo',tipo);if(estado)query.set('estado',estado);
 const list=useFacturas(`facturas?${query}`,!!entityId);const rows=list.data?.pages.flatMap(p=>p.items)||[];
 const closeDetail=()=>{const next=new URLSearchParams(params);next.delete('factura');setParams(next,{replace:true});};
 const open=(id:string)=>{const next=new URLSearchParams(params);next.set('factura',id);setParams(next);};
 return <>
  <div className="fiscal-head"><div><p className="fiscal-eyebrow">ADMINISTRACIÓN · VELAI</p><h1>Facturación</h1><p>Prepara tus borradores y conserva las facturas de cada negocio.</p></div><div className="g-inline"><button type="button" className="btn alt" disabled={!entityId} onClick={()=>setEditor('borrador')}>Preparar borrador</button><button type="button" className="btn" disabled={!entityId} onClick={()=>setEditor('externa')}>Registrar factura externa</button></div></div>
  <Card title="Emisor de Velai"><div className="fiscal-filters"><label>Emisor<select value={entityId} onChange={e=>setEntidad(e.target.value)}><option value="">Seleccionar emisor</option>{cat.data?.entidades.map(e=><option value={e.id} key={e.id}>{e.nombre}</option>)}</select></label><label>Moneda<select value={moneda} onChange={e=>setMoneda(e.target.value as Moneda)}><option value="EUR">EUR · euros</option><option value="COP">COP · pesos colombianos</option></select></label><div className="g-inline"><EntityOptions onDone={()=>void cat.refetch()}/></div></div><FiscalError error={cat.error}/>{cat.isPending?<p role="status">Cargando emisores…</p>:issuer?<p className="fiscal-profile"><strong>{issuer.nombre}</strong><span>{issuer.nif?`NIF: ${issuer.nif}`:'NIF pendiente'} · {issuer.direccion||'Domicilio fiscal pendiente'}</span><span className={`fiscal-tag ${entidadCompleta(issuer)?'is-valid':''}`}>{entidadCompleta(issuer)?'Datos fiscales completos':'Configuración fiscal pendiente'}</span></p>:<p className="g-empty">Añade el emisor de Velai para preparar el primer borrador.</p>}{issuer&&!entidadCompleta(issuer)?<Notice>Puedes guardar y editar borradores ahora. La validación y los cierres se habilitan al completar y verificar los datos fiscales de Velai.</Notice>:null}</Card>
  <Card title="Facturas y borradores" action={<a href="/formatos/Formatos_Factura_Velai.pdf" target="_blank" rel="noreferrer">Ver formato de referencia (sin valor fiscal)</a>}>
   <div className="fiscal-filters"><label>Tipo de factura<select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todas</option><option value="recibida">Recibidas · proveedores</option><option value="emitida">Emitidas · clientes</option></select></label><label>Estado<select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos</option><option value="borrador">Borradores</option><option value="registrada">Pendientes de revisión</option><option value="validada">Validadas</option></select></label></div>
   <FiscalError error={list.error}/>{entityId&&list.isPending?<p role="status">Cargando facturas…</p>:rows.length?<div className="g-table"><table><caption className="fiscal-sr-only">Facturas del emisor y moneda seleccionados</caption><thead><tr><th>Factura</th><th>Cliente o proveedor</th><th>Negocio</th><th>Importe registrado</th><th>Estado</th><th><span className="fiscal-sr-only">Acciones</span></th></tr></thead><tbody>{rows.map(f=><tr key={f.id}><td><strong>{f.numero||'Borrador sin número'}</strong><small>{f.tipo==='recibida'?'Recibida':'Emitida'} · {f.fecha_emision||'Fecha pendiente'}{f.correccion_de?' · Corrección interna':''}</small></td><td>{f.contraparte_nombre||'Por completar'}</td><td>{negocios[f.negocio]}</td><td><Money value={f.total} moneda={f.moneda}/>{f.lineas.some(l=>l.iva_bp===null)?<small>IVA por clasificar</small>:null}</td><td><span className={`fiscal-tag ${f.estado==='validada'?'is-valid':''}`}>{estadoLabels[f.estado]}</span><small>{f.documentos_count?`${f.documentos_count} documento(s)`:'Original pendiente'}</small></td><td><button type="button" className="btn alt" onClick={()=>open(f.id)} aria-label={`Ver ${f.numero||'borrador'}${f.contraparte_nombre?` de ${f.contraparte_nombre}`:''}`}>Ver detalle</button></td></tr>)}</tbody></table></div>:<p className="g-empty">No hay registros para estos filtros. Prepara un borrador o registra una factura que ya exista.</p>}
   {list.hasNextPage?<button type="button" className="btn alt" disabled={list.isFetchingNextPage} onClick={()=>void list.fetchNextPage()}>{list.isFetchingNextPage?'Cargando…':'Cargar más facturas'}</button>:null}
   <Notice>Registrar una factura no registra otro pago. Los cobros y pagos se controlan en tesorería y compras.</Notice>
  </Card>
  <div className="fiscal-bottom"><Link to="/impuestos">Revisar impuestos y preparar el libro para asesoría →</Link><span>Los borradores no son facturas emitidas.</span></div>
  {editor&&entityId?<InvoiceEditor mode={editor} entidadId={entityId} moneda={moneda} close={()=>setEditor(null)} saved={id=>{setEditor(null);open(id);}}/>:null}
  {params.get('factura')?<InvoiceDetail id={params.get('factura')!} entidades={cat.data?.entidades||[]} close={closeDetail} open={open}/>:null}
 </>;
}

type DraftLine={key:string;descripcion:string;cantidad:string;precio:string;descuento:string;iva:string;retencion:string};
const emptyLine=():DraftLine=>({key:crypto.randomUUID(),descripcion:'',cantidad:'1',precio:'',descuento:'0',iva:'',retencion:'0'});
function InvoiceEditor({mode,entidadId,moneda,item,close,saved}:{mode:'borrador'|'externa'|'editar'|'corregir';entidadId:string;moneda:Moneda;item?:Factura;close:()=>void;saved:(id:string)=>void}){
 const save=useGuardar();const [id]=useState(()=>crypto.randomUUID());const [dirty,setDirty]=useState(false),[error,setError]=useState<unknown>(null);
 const [externa,setExterna]=useState(item?item.origen==='externa':mode==='externa'),[tipo,setTipo]=useState(item?.tipo||'emitida'),[clase,setClase]=useState(item?.clase||'ordinaria'),[tratamiento,setTratamiento]=useState<Tratamiento>(item?.tratamiento_fiscal||'pendiente');
 const [compraId,setCompraId]=useState(item?.compra_id||''),[rectificaId,setRectificaId]=useState(item?.rectifica_id||'');
 const [lines,setLines]=useState<DraftLine[]>(()=>item?.lineas.map(l=>({key:crypto.randomUUID(),descripcion:l.descripcion,cantidad:l.cantidad,precio:minorInput(l.precio_unitario,moneda),descuento:minorInput(l.descuento,moneda),iva:l.iva_bp==null?'':String(l.iva_bp/100),retencion:String(l.retencion_bp/100)}))||[emptyLine()]);
 const purchases=useGestion<{items:Compra[];mas?:boolean}>(`compras?entidad_id=${encodeURIComponent(entidadId)}&moneda=${moneda}`,tipo==='recibida');
 const refs=useFacturas(`facturas?${new URLSearchParams({entidad_id:entidadId,moneda,tipo,estado:'validada'})}`,clase==='rectificativa');
 const locked=mode==='corregir'||!!item?.correccion_de;
 const title=mode==='corregir'?'Preparar corrección interna':mode==='editar'?'Editar registro de factura':externa?'Registrar factura externa':'Preparar borrador';
 function setLine(key:string,field:keyof Omit<DraftLine,'key'>,value:string){setDirty(true);setLines(current=>current.map(l=>l.key===key?{...l,[field]:value}:l));}
 async function send(e:FormEvent<HTMLFormElement>){
  e.preventDefault();if(save.isPending)return;setError(null);const d=new FormData(e.currentTarget);
  try{
   const lineas=lines.map(l=>{const cantidad=l.cantidad.trim().replace(',','.');if(!/^\d{1,7}(?:\.\d{1,4})?$/.test(cantidad)||Number(cantidad)<=0)throw new Error('cantidad_invalida');return {descripcion:l.descripcion.trim(),cantidad,precio_unitario:parseMinor(l.precio,moneda,clase==='rectificativa'),descuento:parseMinor(l.descuento||'0',moneda),iva_bp:tratamiento==='rebu'?null:parseRate(l.iva,true),retencion_bp:parseRate(l.retencion)};});
   const body={entidad_id:entidadId,moneda,negocio:str(d,'negocio'),tipo:locked?item!.tipo:tipo,estado:externa?'registrada':'borrador',origen:externa?'externa':'borrador',clase:locked?item!.clase:clase,tratamiento_fiscal:tratamiento,
    contraparte_nombre:opt(d,'contraparte_nombre'),contraparte_nif:locked?item!.contraparte_nif:opt(d,'contraparte_nif'),contraparte_direccion:opt(d,'contraparte_direccion'),
    numero:locked?item!.numero:externa?opt(d,'numero'):null,fecha_emision:locked?item!.fecha_emision:opt(d,'fecha_emision'),fecha_operacion:locked?item!.fecha_operacion:opt(d,'fecha_operacion'),fecha_recepcion:opt(d,'fecha_recepcion'),
    nota:opt(d,'nota'),nota_fiscal:opt(d,'nota_fiscal'),proveedor_emision:opt(d,'proveedor_emision'),compra_id:tipo==='recibida'?opt(d,'compra_id'):null,rectifica_id:locked?item!.rectifica_id:clase==='rectificativa'?opt(d,'rectifica_id'):null,lineas};
   const result=await save.mutateAsync(mode==='corregir'?{path:`facturas/${item!.id}/corregir`,body:{...body,id,version:item!.version,motivo:str(d,'motivo')}}:mode==='editar'?{path:`facturas/${item!.id}`,method:'PATCH',body:{...body,version:item!.version}}:{path:'facturas',body:{...body,id}}) as {item:Factura};
   saved(result.item.id);
  }catch(err){setError(err);}
 }
 return <Modal title={title} close={close} dirty={dirty} busy={save.isPending}><form className="fiscal-editor" onSubmit={e=>void send(e)} onChange={()=>setDirty(true)}><fieldset disabled={save.isPending}>
  {mode==='corregir'?<><Notice>Esta corrección conserva el original validado. La revisión anterior permanece en el libro hasta validar la nueva; adjunta también su evidencia. No crea una factura rectificativa legal.</Notice><Fields fields={[{name:'motivo',label:'Motivo de la corrección interna',type:'textarea',required:true}]}/></>:null}
  <div className="g-fields"><label>Tipo de registro<select value={externa?'externa':'borrador'} disabled={locked} onChange={e=>setExterna(e.target.value==='externa')}><option value="borrador">Borrador interno · sin valor fiscal</option><option value="externa">Factura que ya existe fuera de Velai</option></select></label><label>Tipo de factura<select value={tipo} disabled={locked} onChange={e=>setTipo(e.target.value as 'recibida'|'emitida')}><option value="emitida">Emitida · cliente</option><option value="recibida">Recibida · proveedor</option></select></label></div>
  <Fields fields={[{name:'negocio',label:'Negocio',value:item?.negocio||'velai',options:Object.entries(negocios).map(([value,label])=>({value,label}))}]}/>
  <div className="g-fields"><label>Clase de documento<select value={clase} disabled={locked} onChange={e=>setClase(e.target.value as 'ordinaria'|'rectificativa')}><option value="ordinaria">Ordinaria</option><option value="rectificativa">Rectificativa externa</option></select></label><label>Tratamiento fiscal<select value={tratamiento} onChange={e=>setTratamiento(e.target.value as Tratamiento)}>{Object.entries(tratamientoLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
  {['rebu','inversion'].includes(tratamiento)?<Notice>Puedes conservar el registro y el original. Este régimen requiere asesoría y aún no se incorpora al cálculo fiscal de esta sección.</Notice>:null}
  {clase==='rectificativa'?<><fieldset disabled={locked}><label className="fiscal-full-label">Factura validada que rectifica<select name="rectifica_id" value={rectificaId} onChange={e=>setRectificaId(e.target.value)} required={externa}><option value="">Seleccionar original</option>{item?.rectifica_id&&!refs.data?.pages.some(p=>p.items.some(f=>f.id===item.rectifica_id))?<option value={item.rectifica_id}>Original vinculado anteriormente</option>:null}{refs.data?.pages.flatMap(p=>p.items).map(f=><option value={f.id} key={f.id}>{f.numero||'Sin número'} · {f.contraparte_nombre||'Sin nombre'}</option>)}</select></label></fieldset><FiscalError error={refs.error}/>{refs.hasNextPage?<button type="button" className="btn alt" disabled={refs.isFetchingNextPage} onClick={()=>void refs.fetchNextPage()}>Cargar más originales</button>:null}<p className="fiscal-help">Registra el número y las líneas del documento rectificativo real, con el signo de sus importes.</p></>:null}
  <h3>{tipo==='recibida'?'Proveedor':'Cliente'}</h3><Fields fields={[{name:'contraparte_nombre',label:'Nombre o razón social',value:item?.contraparte_nombre},{name:'contraparte_direccion',label:'Domicilio fiscal',value:item?.contraparte_direccion}]}/>
  <fieldset disabled={locked}><Fields fields={[{name:'contraparte_nif',label:'NIF o identificación fiscal',value:item?.contraparte_nif},...(externa?[{name:'numero',label:'Número exacto del original',value:item?.numero,required:true}]:[]),{name:'fecha_emision',label:externa?'Fecha de expedición del original':'Fecha prevista (opcional)',type:'date',value:item?.fecha_emision,required:externa},{name:'fecha_operacion',label:'Fecha de operación',type:'date',value:item?.fecha_operacion}]}/></fieldset>
  {tipo==='recibida'?<><Fields fields={[{name:'fecha_recepcion',label:'Fecha de recepción',type:'date',value:item?.fecha_recepcion}]}/><label className="fiscal-full-label">Compra relacionada (opcional)<select name="compra_id" value={compraId} onChange={e=>setCompraId(e.target.value)}><option value="">Sin vincular</option>{item?.compra_id&&!purchases.data?.items.some(p=>p.id===item.compra_id)?<option value={item.compra_id}>Compra vinculada anteriormente</option>:null}{purchases.data?.items?.filter(p=>p.entidad_id===entidadId&&p.moneda===moneda).map(p=><option value={p.id} key={p.id}>{p.concepto}</option>)}</select></label><FiscalError error={purchases.error}/>{purchases.data?.mas?<p className="fiscal-help">Se muestran las compras más recientes. Una compra ya vinculada se conserva aunque no aparezca en esta lista.</p>:null}</>:null}
  <div className="fiscal-lines-heading"><h3>Líneas · {moneda}</h3><button type="button" className="btn alt" disabled={lines.length>=100} onClick={()=>{setDirty(true);setLines(old=>[...old,emptyLine()]);}}>Añadir línea</button></div>
  <p className="fiscal-help">{tratamiento==='rebu'?'Registra el precio final del original REBU, sin separar una cuota de IVA. La revisión del régimen queda pendiente de asesoría.':'Escribe el precio sin IVA y el descuento total de cada línea. Deja el IVA pendiente si aún no se ha clasificado; no se asumirá el 21 %.'}</p>
  {lines.map((l,index)=><fieldset className="fiscal-line" key={l.key}><legend>Línea {index+1}</legend><label className="fiscal-description">Descripción<input value={l.descripcion} onChange={e=>setLine(l.key,'descripcion',e.target.value)} maxLength={500} required/></label><div className="fiscal-line-values"><label>Cantidad<input aria-label={`Cantidad línea ${index+1}`} inputMode="decimal" value={l.cantidad} onChange={e=>setLine(l.key,'cantidad',e.target.value)} required/></label><label>{tratamiento==='rebu'?'Precio final':'Precio sin IVA'} ({moneda})<input aria-label={`Precio línea ${index+1} (${moneda})`} inputMode="decimal" value={l.precio} onChange={e=>setLine(l.key,'precio',e.target.value)} required/></label><label>Descuento ({moneda})<input aria-label={`Descuento línea ${index+1} (${moneda})`} inputMode="decimal" value={l.descuento} onChange={e=>setLine(l.key,'descuento',e.target.value)}/></label><label>IVA (%)<input disabled={tratamiento==='rebu'} aria-label={`IVA línea ${index+1} (%)`} inputMode="decimal" placeholder={tratamiento==='rebu'?'Sin desglose':'Pendiente'} value={tratamiento==='rebu'?'':l.iva} onChange={e=>setLine(l.key,'iva',e.target.value)}/></label><label>Retención (%)<input aria-label={`Retención línea ${index+1} (%)`} inputMode="decimal" value={l.retencion} onChange={e=>setLine(l.key,'retencion',e.target.value)}/></label></div><button type="button" className="btn alt" aria-label={`Quitar línea ${index+1}`} disabled={lines.length===1} onClick={()=>{setDirty(true);setLines(old=>old.filter(row=>row.key!==l.key));}}>Quitar línea</button></fieldset>)}
  <Fields fields={[{name:'nota_fiscal',label:'Fundamento o aclaración fiscal',type:'textarea',value:item?.nota_fiscal,required:['exento','no_sujeto'].includes(tratamiento),help:'Indica el fundamento si la operación es exenta o no sujeta.'},{name:'proveedor_emision',label:'Programa que emitió el original (opcional)',value:item?.proveedor_emision},{name:'nota',label:'Nota interna',type:'textarea',value:item?.nota}]}/>
  <Notice>El servidor recalcula los importes al guardar. Después puedes revisar el detalle y adjuntar el documento original. Guardar no emite una factura ni registra un pago.</Notice>
 </fieldset><FiscalError error={error}/><div className="g-form-actions"><button className="btn" disabled={save.isPending}>{save.isPending?'Guardando…':mode==='corregir'?'Guardar corrección interna':externa?'Guardar registro':'Guardar borrador'}</button></div></form></Modal>;
}

function InvoiceDetail({id,entidades,close,open}:{id:string;entidades:Entidad[];close:()=>void;open:(id:string)=>void}){
 const query=useGestion<{item:Factura}>(`facturas/${encodeURIComponent(id)}`);const save=useGuardar();const [edit,setEdit]=useState<'editar'|'corregir'|null>(null),[validar,setValidar]=useState(false);
 const f=query.data?.item;const issuer=entidades.find(e=>e.id===f?.entidad_id);const frozen=f?.snapshot?.entidad;
 const reasons=f?[
  ...(!entidadCompleta(issuer)?['Completa y verifica los datos fiscales de Velai.']:[]),
  ...(f.origen!=='externa'||f.estado==='borrador'?['Registra primero los datos de una factura externa real.']:[]),
  ...(!f.numero||!f.fecha_emision||!f.contraparte_nombre||!f.contraparte_nif||!f.contraparte_direccion?['Completa la identificación, el número y las fechas del original.']:[]),
  ...(!f.originales_count?['Adjunta la factura original con el tipo de documento «Factura».']:[]),
  ...(f.clase==='rectificativa'&&!f.rectifica_id?['Vincula la factura original que rectifica.']:[]),
  ...(f.tratamiento_fiscal==='pendiente'?['Clasifica el tratamiento fiscal.']:[]),
  ...(['rebu','inversion'].includes(f.tratamiento_fiscal)?['Este régimen requiere asesoría y no se valida en el libro general.']:[]),
  ...(f.tratamiento_fiscal==='general'&&f.lineas.some(l=>l.iva_bp===null)?['Indica el IVA de todas las líneas.']:[]),
  ...(['exento','no_sujeto'].includes(f.tratamiento_fiscal)&&!f.nota_fiscal?['Documenta el fundamento fiscal.']:[]),
 ]:[];
 return <Modal key={id} title={f?.numero?`Factura ${f.numero}`:'Detalle de factura'} close={close}><FiscalError error={query.error}/>{query.isPending?<p role="status">Cargando detalle…</p>:f?<>
  <div className="fiscal-detail-top"><span className={`fiscal-tag ${f.estado==='validada'?'is-valid':''}`}>{estadoLabels[f.estado]}</span><strong>{frozen?.nombre||issuer?.nombre||'Emisor de Velai'}</strong><span>{f.moneda} · {negocios[f.negocio]} · {f.tipo==='recibida'?'Recibida':'Emitida'}</span></div>
  <dl className="fiscal-detail-grid"><div><dt>Cliente o proveedor</dt><dd>{f.contraparte_nombre||'Pendiente'}</dd></div><div><dt>Identificación fiscal</dt><dd>{f.contraparte_nif||'Pendiente'}</dd></div><div><dt>Domicilio</dt><dd>{f.contraparte_direccion||'Pendiente'}</dd></div><div><dt>Fecha de expedición / operación</dt><dd>{f.fecha_emision||'Pendiente'} / {f.fecha_operacion||'Sin fecha distinta'}</dd></div><div><dt>Tratamiento fiscal</dt><dd>{tratamientoLabels[f.tratamiento_fiscal]}</dd></div><div><dt>Documento</dt><dd>{f.clase==='rectificativa'?'Rectificativa externa':'Ordinario'} · {f.origen==='externa'?'Original externo':'Borrador interno'}</dd></div></dl>
  <div className="g-table"><table><caption className="fiscal-sr-only">Líneas e importes calculados por el servidor</caption><thead><tr><th>Concepto</th><th>Cantidad</th><th>{f.tratamiento_fiscal==='rebu'?'Importe final':'Base'}</th><th>IVA</th><th>Retención</th><th>Total</th></tr></thead><tbody>{f.lineas.map((l,i)=><tr key={i}><td>{l.descripcion}</td><td>{l.cantidad}</td><td><Money value={l.base} moneda={f.moneda}/></td><td>{l.iva_bp===null?(f.tratamiento_fiscal==='rebu'?'Sin desglose':'Pendiente'):<><Money value={l.iva} moneda={f.moneda}/><small>{l.iva_bp/100} %</small></>}</td><td><Money value={l.retencion} moneda={f.moneda}/></td><td><Money value={l.total} moneda={f.moneda}/></td></tr>)}</tbody></table></div>
  <div className="fiscal-detail-totals"><span>Importe registrado<strong><Money value={f.total} moneda={f.moneda}/></strong></span>{f.tipo==='recibida'?<span>IVA deducible revisado<strong><Money value={f.iva_deducible} moneda={f.moneda}/></strong></span>:null}</div>
  {f.tratamiento_fiscal!=='rebu'&&f.lineas.some(l=>l.iva_bp===null)?<Notice>El IVA pendiente no está incluido en el importe registrado. Revisa el tratamiento antes de validar.</Notice>:null}
  {f.nota_fiscal?<p><strong>Aclaración fiscal:</strong> {f.nota_fiscal}</p>:null}{f.nota?<p><strong>Nota interna:</strong> {f.nota}</p>:null}
  {f.correccion_de?<p>Corrección interna de <button type="button" className="fiscal-text-button" onClick={()=>open(f.correccion_de!)}>ver registro anterior</button>. {f.motivo_correccion}</p>:null}{f.rectifica_id?<p>Documento rectificativo relacionado: <button type="button" className="fiscal-text-button" onClick={()=>open(f.rectifica_id!)}>Ver factura original</button></p>:null}
  {f.estado==='validada'?<Notice>Original validado e inmutable. {f.revision}{f.snapshot?` Revisado por ${f.snapshot.revisada_por}, ${new Date(f.snapshot.revisada_en).toLocaleString('es-ES')}.`:''}</Notice>:reasons.length?<div className="fiscal-pending"><strong>Para validar faltan estos pasos</strong><ul>{reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>:null}
  <div className="g-inline fiscal-detail-actions">{f.estado==='validada'?<button type="button" className="btn alt" onClick={()=>setEdit('corregir')}>Preparar corrección interna</button>:<><button type="button" className="btn alt" onClick={()=>setEdit('editar')}>Editar registro</button><button type="button" className="btn" disabled={reasons.length>0} onClick={()=>setValidar(true)}>Revisar y validar</button></>}</div>
  <Documentos tipo="factura" objetoId={f.id}/>
  {edit?<InvoiceEditor mode={edit} entidadId={f.entidad_id} moneda={f.moneda} item={f} close={()=>setEdit(null)} saved={newId=>{setEdit(null);if(newId!==id)open(newId);}}/>:null}
  {validar?<FormModal title="Validar el original y su tratamiento fiscal" close={()=>setValidar(false)} label="Confirmar revisión" fields={[...(f.tipo==='recibida'?[{name:'iva_deducible',label:`IVA deducible revisado (${f.moneda})`,value:'0',required:true,help:'Por defecto, cero. Confirma con asesoría qué cuota resulta deducible.'}]:[]),{name:'revision',label:'Qué se revisó y fundamento de la deducción',type:'textarea',required:true}]} submit={d=>save.mutateAsync({path:`facturas/${f.id}/validar`,body:{version:f.version,iva_deducible:f.tipo==='recibida'?parseMinor(str(d,'iva_deducible'),f.moneda,true):0,revision:str(d,'revision')}})}><Notice>La validación conserva una copia de los datos y las referencias a los originales. No acredita el pago ni presenta impuestos.</Notice></FormModal>:null}
 </>:null}</Modal>;
}
