import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router';
import { afterEach, expect, it, vi } from 'vitest';
import { ConfirmarHost } from '../../components/Confirmar';
import { Facturacion, parseMinor, type Factura } from './Facturacion';
const E='00000000-0000-4000-8000-000000000001',F='00000000-0000-4000-8000-000000000002';
const factura:Factura={id:F,entidad_id:E,moneda:'EUR',negocio:'velai',tipo:'recibida',estado:'registrada',origen:'externa',clase:'ordinaria',tratamiento_fiscal:'general',contraparte_nombre:'Proveedor de ejemplo',contraparte_nif:'NIF-EJEMPLO',contraparte_direccion:'Domicilio de ejemplo',numero:'ORIGINAL-1',fecha_emision:'2026-10-09',fecha_operacion:'2026-10-09',fecha_recepcion:'2026-10-09',compra_id:null,proveedor_emision:null,nota:null,nota_fiscal:null,rectifica_id:null,correccion_de:null,motivo_correccion:null,base:10000,iva:2100,retencion:0,total:12100,iva_deducible:0,lineas:[{descripcion:'Servicio de prueba',cantidad:'1',precio_unitario:10000,descuento:0,iva_bp:2100,retencion_bp:0,base:10000,iva:2100,retencion:0,total:12100}],documentos_count:1,originales_count:1,version:2,revision:null,snapshot:null};
function mount({path='/facturacion',item=factura,socio=true,failFirst=false,active=true}={}){
 const calls:{path:string;method:string;body?:Record<string,unknown>}[]=[];let writes=0;let saved=item;
 vi.stubGlobal('fetch',vi.fn(async(input:string,init?:RequestInit)=>{const u=new URL(String(input),'https://panel.test'),method=init?.method||'GET',body=init?.body?JSON.parse(String(init.body)):undefined;calls.push({path:u.pathname+u.search,method,body});
 if(method!=='GET'){if(failFirst&&++writes===1)return Response.json({error:'network_failed'},{status:503});saved={...saved,...body,id:body.id||saved.id};return Response.json({item:saved});}
 if(u.pathname==='/api/admin/me')return Response.json({role:socio?'velai':'cliente',socio});
 if(u.pathname.endsWith('/catalogos'))return Response.json({entidades:[{id:E,nombre:'Velai provisional',tipo:'sociedad',nif:active?'NIF-VELAI':null,direccion:active?'Dirección Velai':null,estado:active?'activa':'pendiente',version:1}],cuentas:[],socios:[],negocios:['velai','coches','dialogos','comun']});
 if(u.pathname.endsWith('/documentos')||u.pathname.endsWith('/compras'))return Response.json({items:[]});
 if(u.pathname.endsWith('/facturas'))return Response.json({items:[saved],nextCursor:null});if(u.pathname.includes('/facturas/'))return Response.json({item:saved});return Response.json({});}));
 const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path="/facturacion" element={<Facturacion/>}/><Route path="/" element={<h1>Inicio</h1>}/></Routes><ConfirmarHost/></MemoryRouter></QueryClientProvider>);return{user:userEvent.setup(),calls};
}
afterEach(()=>vi.unstubAllGlobals());
it('bloquea al cliente sin consultar gestión',async()=>{const {calls}=mount({socio:false});await screen.findByRole('heading',{name:'Inicio'});expect(calls.some(c=>c.path.includes('/gestion/'))).toBe(false);});
it('guarda borrador con importe exacto, IVA pendiente y sin número fiscal',async()=>{const {user,calls}=mount({active:false});await user.click(await screen.findByRole('button',{name:'Preparar borrador'}));const d=within(screen.getByRole('dialog',{name:'Preparar borrador'}));await user.type(d.getByLabelText('Descripción'),'Mantenimiento');await user.type(d.getByLabelText('Precio línea 1 (EUR)'),'100,25');expect(d.getByLabelText('IVA línea 1 (%)')).toHaveValue('');await user.click(d.getByRole('button',{name:'Guardar borrador'}));await waitFor(()=>expect(calls.some(c=>c.method==='POST')).toBe(true));expect(calls.find(c=>c.method==='POST')?.body).toMatchObject({entidad_id:E,origen:'borrador',estado:'borrador',numero:null,tratamiento_fiscal:'pendiente',lineas:[{precio_unitario:10025,iva_bp:null,retencion_bp:0,cantidad:'1'}]});});
it('conserva datos e identificador al reintentar un fallo',async()=>{const {user,calls}=mount({failFirst:true});await user.click(await screen.findByRole('button',{name:'Preparar borrador'}));const d=within(screen.getByRole('dialog',{name:'Preparar borrador'}));await user.type(d.getByLabelText('Descripción'),'Servicio conservado');await user.type(d.getByLabelText('Precio línea 1 (EUR)'),'55');await user.click(d.getByRole('button',{name:'Guardar borrador'}));expect(await d.findByRole('alert')).toHaveTextContent('Tus datos siguen aquí');expect(d.getByLabelText('Descripción')).toHaveValue('Servicio conservado');await user.click(d.getByRole('button',{name:'Guardar borrador'}));await waitFor(()=>expect(calls.filter(c=>c.method==='POST')).toHaveLength(2));const w=calls.filter(c=>c.method==='POST');expect(w[0]?.body?.id).toBe(w[1]?.body?.id);});
it('envía el filtro de recibidas al servidor antes de paginar',async()=>{const {user,calls}=mount();await screen.findByRole('button',{name:'Registrar factura externa'});await user.selectOptions(screen.getByLabelText('Tipo de factura'),'recibida');await waitFor(()=>expect(calls.some(c=>c.path.includes('/facturas?')&&c.path.includes('tipo=recibida'))).toBe(true));});
it('un justificante sin original no habilita la validación',async()=>{mount({path:`/facturacion?factura=${F}`,item:{...factura,originales_count:0}});const d=within(await screen.findByRole('dialog',{name:'Factura ORIGINAL-1'}));expect(d.getByRole('button',{name:'Revisar y validar'})).toBeDisabled();expect(d.getByText(/tipo de documento «Factura»/)).toBeInTheDocument();});
it('la revisión inicia deducción cero y exige un fundamento',async()=>{const {user,calls}=mount({path:`/facturacion?factura=${F}`});await user.click(await screen.findByRole('button',{name:'Revisar y validar'}));const d=within(screen.getByRole('dialog',{name:'Validar el original y su tratamiento fiscal'}));expect(d.getByLabelText(/IVA deducible revisado/)).toHaveValue('0');await user.type(d.getByLabelText('Qué se revisó y fundamento de la deducción'),'Original revisado; deducción pendiente.');await user.click(d.getByRole('button',{name:'Confirmar revisión'}));await waitFor(()=>expect(calls.some(c=>c.path.endsWith('/validar'))).toBe(true));expect(calls.find(c=>c.path.endsWith('/validar'))?.body).toMatchObject({version:2,iva_deducible:0,revision:'Original revisado; deducción pendiente.'});});
it('una validada se corrige sin modificar la identidad del original',async()=>{const {user,calls}=mount({path:`/facturacion?factura=${F}`,item:{...factura,estado:'validada'}});await user.click(await screen.findByRole('button',{name:'Preparar corrección interna'}));const d=within(screen.getByRole('dialog',{name:'Preparar corrección interna'}));expect(d.getByLabelText('Número exacto del original')).toBeDisabled();await user.type(d.getByLabelText('Motivo de la corrección interna'),'Corregir importe transcrito.');await user.clear(d.getByLabelText('Precio línea 1 (EUR)'));await user.type(d.getByLabelText('Precio línea 1 (EUR)'),'90');await user.click(d.getByRole('button',{name:'Guardar corrección interna'}));await waitFor(()=>expect(calls.some(c=>c.path.endsWith('/corregir'))).toBe(true));expect(calls.find(c=>c.path.endsWith('/corregir'))?.body).toMatchObject({numero:'ORIGINAL-1',contraparte_nif:'NIF-EJEMPLO',fecha_emision:'2026-10-09',version:2,motivo:'Corregir importe transcrito.',lineas:[{precio_unitario:9000}]});expect(calls.some(c=>c.method==='PATCH')).toBe(false);});
it('REBU conserva precio final sin proponer desglose de IVA',async()=>{const {user,calls}=mount();await user.click(await screen.findByRole('button',{name:'Preparar borrador'}));const d=within(screen.getByRole('dialog',{name:'Preparar borrador'}));await user.selectOptions(d.getByLabelText('Tratamiento fiscal'),'rebu');expect(d.getByLabelText('IVA línea 1 (%)')).toBeDisabled();await user.type(d.getByLabelText('Descripción'),'Vehículo usado');await user.type(d.getByLabelText('Precio línea 1 (EUR)'),'12100');await user.click(d.getByRole('button',{name:'Guardar borrador'}));await waitFor(()=>expect(calls.some(c=>c.method==='POST')).toBe(true));expect(calls.find(c=>c.method==='POST')?.body).toMatchObject({tratamiento_fiscal:'rebu',lineas:[{precio_unitario:1210000,iva_bp:null}]});});
it('convierte decimales exactos y rechaza negativos ordinarios',()=>{expect(parseMinor('0,29','EUR')).toBe(29);expect(parseMinor('-12.01','EUR',true)).toBe(-1201);expect(parseMinor('1000','COP')).toBe(1000);expect(()=>parseMinor('-1','EUR')).toThrow();expect(()=>parseMinor('1.001','EUR')).toThrow();});
it('registra un original externo con su número y fecha sin generar otra factura',async()=>{const {user,calls}=mount();await user.click(await screen.findByRole('button',{name:'Registrar factura externa'}));const d=within(screen.getByRole('dialog',{name:'Registrar factura externa'}));await user.selectOptions(d.getByLabelText('Tipo de factura'),'recibida');await user.type(d.getByLabelText('Número exacto del original'),'PROVEEDOR-2026-9');await user.type(d.getByLabelText('Fecha de expedición del original'),'2026-10-09');await user.type(d.getByLabelText('Descripción'),'Compra de equipos');await user.type(d.getByLabelText('Precio línea 1 (EUR)'),'796,75');await user.click(d.getByRole('button',{name:'Guardar registro'}));await waitFor(()=>expect(calls.some(c=>c.method==='POST')).toBe(true));expect(calls.find(c=>c.method==='POST')?.body).toMatchObject({tipo:'recibida',origen:'externa',estado:'registrada',numero:'PROVEEDOR-2026-9',fecha_emision:'2026-10-09',lineas:[{iva_bp:null}]});expect(calls.some(c=>c.path.includes('/movimientos'))).toBe(false);});
it('editar conserva la compra vinculada aunque no esté en la lista reciente',async()=>{const compra='00000000-0000-4000-8000-000000000004';const {user,calls}=mount({path:`/facturacion?factura=${F}`,item:{...factura,compra_id:compra}});await user.click(await screen.findByRole('button',{name:'Editar registro'}));const d=within(screen.getByRole('dialog',{name:'Editar registro de factura'}));expect(d.getByLabelText('Compra relacionada (opcional)')).toHaveValue(compra);await user.click(d.getByRole('button',{name:'Guardar registro'}));await waitFor(()=>expect(calls.some(c=>c.method==='PATCH')).toBe(true));expect(calls.find(c=>c.method==='PATCH')?.body?.compra_id).toBe(compra);});
