import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { afterEach, expect, it, vi } from 'vitest';
import { Fondos } from './Fondos';
function mount({empty=false,error=false}={}){const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(input:string)=>{const u=new URL(String(input),'https://panel.test');calls.push(u.pathname+u.search);if(u.pathname==='/api/admin/me')return Response.json({role:'velai',socio:true});if(u.pathname.endsWith('/catalogos'))return Response.json({entidades:[],cuentas:[],socios:[],negocios:[]});if(error)return Response.json({error:'network_failed'},{status:503});const moneda=u.searchParams.get('moneda')||'EUR';return Response.json({moneda,cuentas:empty?[]:[{id:'cuenta',nombre:'Cuenta común',moneda,entidad_id:null,saldo_inicial:0,fecha_saldo:null,conciliada:0,version:1,movimientos:100000,saldo:100000,reserva:10000,disponible:90000,estado_saldo:'pendiente'}],compras:{por_negocio:empty?[]:[{negocio:'dialogos',previsto:30000,comprometido:0,comprado:79675,pagado:79675,pendiente:20000}],previsto:empty?0:30000,pendiente:empty?0:20000},socios:empty?[]:[{email:'socio@velai.test',nombre:'Socio de ejemplo',adelantado:8000,reembolsado:3000,saldo:5000}],totales:{saldo:empty?0:100000,reservas:empty?0:10000,disponible:empty?0:90000,saldo_conciliado:0,saldo_pendiente_conciliar:empty?0:100000,deuda_pendiente:0,deuda_sin_desembolsar:0,compromisos_pendientes:empty?0:20000,previsto:empty?0:30000,saldo_socios:empty?0:5000,disponible_tras_compromisos:empty?0:65000}});}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter><Fondos/></MemoryRouter></QueryClientProvider>);return{user:userEvent.setup(),calls};}
afterEach(()=>vi.unstubAllGlobals());
it('usa el disponible de API sin descontar dos veces los adelantos',async()=>{mount();const metrics=await screen.findByLabelText('Fondos registrados');expect(within(metrics).getByText('€ 650,00')).toBeInTheDocument();expect(within(metrics).queryByText('€ 600,00')).not.toBeInTheDocument();expect(screen.getByText('Menos adelantos por devolver a socios')).toBeInTheDocument();expect(screen.getByText('Pendiente de conciliar')).toBeInTheDocument();expect(screen.getByText(/Contrástalo con el extracto bancario/)).toBeInTheDocument();});
it('separa monedas y actualiza la consulta del gráfico',async()=>{const {user,calls}=mount();await screen.findByLabelText('Fondos registrados');await user.selectOptions(screen.getByLabelText('Moneda de los fondos'),'COP');await waitFor(()=>expect(calls).toContain('/api/admin/gestion/resumen?moneda=COP'));await user.selectOptions(screen.getByLabelText('Importes del gráfico'),'pendiente');expect(await screen.findByRole('meter',{name:'Compromisos pendientes de Diálogos (COP)'})).toHaveAttribute('value','20000');});
it('presenta el vacío sin inventar movimientos o socios',async()=>{mount({empty:true});expect(await screen.findByText(/No hay cuentas en esta moneda/)).toBeInTheDocument();expect(screen.getByText('No hay adelantos personales registrados en esta moneda.')).toBeInTheDocument();expect(screen.queryByRole('meter')).not.toBeInTheDocument();});
it('un fallo no se convierte en saldo cero',async()=>{mount({error:true});expect(await screen.findByRole('alert')).toHaveTextContent('No pudimos conectar');expect(screen.queryByLabelText('Fondos registrados')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Reintentar consulta'})).toBeInTheDocument();});
