import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router';
import { afterEach, expect, it, vi } from 'vitest';
import { ConfirmarHost } from '../../components/Confirmar';
import { Impuestos, trimestreActual } from './Impuestos';
const E='00000000-0000-4000-8000-000000000001',C='00000000-0000-4000-8000-000000000003';
function mount({active=true,incidents=false}={}){const calls:{path:string;method:string;body?:Record<string,unknown>}[]=[];const totales={base_emitida:10000,base_recibida:5000,iva_repercutido:2100,iva_soportado:1050,iva_deducible:500,retenciones_emitidas:0,retenciones_recibidas:0,saldo_iva_provisional:1600};const resumen={ambito:{entidad_id:E,moneda:'EUR',desde:'2026-10-01',hasta:'2026-12-31'},totales,validadas:2,pendientes:incidents?1:0,borradores:0,sin_fecha:incidents?1:0,incidencias:incidents?[{id:'factura-pendiente',codigo:'original_pendiente'}]:[],alcance:'Libro interno'};const cierre={id:C,entidad_id:E,moneda:'EUR',desde:'2026-07-01',hasta:'2026-09-30',estado:'cerrado',version:3,sha256:'a'.repeat(64),nota:null,created_by:'socio@velai.test',created_at:'2026-10-01T12:00:00Z',snapshot:{...resumen,entidad:{nombre:'Velai de ejemplo',nif:'NIF-VELAI',direccion:'Domicilio de ejemplo'},facturas:[]}};
vi.stubGlobal('fetch',vi.fn(async(input:string,init?:RequestInit)=>{const u=new URL(String(input),'https://panel.test'),method=init?.method||'GET',body=init?.body?JSON.parse(String(init.body)):undefined;calls.push({path:u.pathname+u.search,method,body});if(method!=='GET')return Response.json({item:{...cierre,...body}});if(u.pathname==='/api/admin/me')return Response.json({role:'velai',socio:true});if(u.pathname.endsWith('/catalogos'))return Response.json({entidades:[{id:E,nombre:'Velai de ejemplo',tipo:'sociedad',nif:active?'NIF-VELAI':null,direccion:active?'Domicilio de ejemplo':null,estado:active?'activa':'pendiente',version:1}],cuentas:[],socios:[],negocios:[]});if(u.pathname.endsWith('/fiscal/resumen'))return Response.json(resumen);if(u.pathname.endsWith('/cierres'))return Response.json({items:[cierre],nextCursor:null});return Response.json({});}));const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/impuestos']}><Routes><Route path="/impuestos" element={<Impuestos/>}/></Routes><ConfirmarHost/></MemoryRouter></QueryClientProvider>);return{user:userEvent.setup(),calls};}
afterEach(()=>vi.unstubAllGlobals());
it('usa fechas civiles para el trimestre',()=>{expect(trimestreActual(new Date(2026,9,9))).toEqual({desde:'2026-10-01',hasta:'2026-12-31'});expect(trimestreActual(new Date(2024,1,29))).toEqual({desde:'2024-01-01',hasta:'2024-03-31'});});
it('exporta el ámbito seleccionado e identifica su carácter interno',async()=>{const {user,calls}=mount();await screen.findByText('Saldo de IVA provisional');expect(screen.getAllByText(/16,00/).length).toBeGreaterThan(0);await user.clear(screen.getByLabelText('Desde'));await user.type(screen.getByLabelText('Desde'),'2026-01-01');await user.clear(screen.getByLabelText('Hasta'));await user.type(screen.getByLabelText('Hasta'),'2026-03-31');await user.selectOptions(screen.getByLabelText('Moneda'),'COP');await waitFor(()=>expect(calls.some(c=>c.path.includes('fiscal/resumen?')&&c.path.includes('moneda=COP')&&c.path.includes('desde=2026-01-01'))).toBe(true));const link=await screen.findByRole('link',{name:'Descargar CSV para asesoría'});expect(Object.fromEntries(new URL(link.getAttribute('href')!,'https://panel.test').searchParams)).toEqual({entidad_id:E,moneda:'COP',desde:'2026-01-01',hasta:'2026-03-31'});expect(screen.getByText(/no presenta una declaración ni paga impuestos/)).toBeInTheDocument();});
it('impide cerrar un emisor fiscal incompleto',async()=>{mount({active:false});expect(await screen.findByRole('button',{name:'Cerrar período interno'})).toBeDisabled();expect(screen.getByText(/emisor todavía está pendiente/)).toBeInTheDocument();});
it('el cierre con incidencias requiere aceptación expresa',async()=>{const {user,calls}=mount({incidents:true});await user.click(await screen.findByRole('button',{name:'Cerrar período interno'}));const d=within(screen.getByRole('dialog',{name:'Cerrar período interno'}));await user.click(d.getByRole('button',{name:'Confirmar cierre interno'}));expect(calls.filter(c=>c.method==='POST')).toHaveLength(0);expect(d.getByRole('checkbox')).not.toBeChecked();await user.click(d.getByRole('checkbox'));await user.click(d.getByRole('button',{name:'Confirmar cierre interno'}));await waitFor(()=>expect(calls.some(c=>c.method==='POST')).toBe(true));expect(calls.find(c=>c.method==='POST')?.body).toMatchObject({entidad_id:E,moneda:'EUR',aceptar_pendientes:true});});
it('la reapertura exige motivo y envía la versión del cierre',async()=>{const {user,calls}=mount();await user.click(await screen.findByRole('button',{name:'Reabrir'}));const d=within(screen.getByRole('dialog',{name:'Reabrir período interno'}));await user.type(d.getByLabelText(/Motivo de la reapertura/),'abc');await user.click(d.getByRole('button',{name:'Reabrir con motivo'}));expect(calls.filter(c=>c.method==='POST')).toHaveLength(0);await user.clear(d.getByLabelText(/Motivo de la reapertura/));await user.type(d.getByLabelText(/Motivo de la reapertura/),'Incorporar la factura que faltaba.');await user.click(d.getByRole('button',{name:'Reabrir con motivo'}));await waitFor(()=>expect(calls.some(c=>c.path.endsWith('/reabrir'))).toBe(true));expect(calls.find(c=>c.path.endsWith('/reabrir'))?.body).toEqual({version:3,motivo:'Incorporar la factura que faltaba.'});});
it('el cierre muestra la copia conservada sin afirmar presentación',async()=>{const {user}=mount();await user.click(await screen.findByRole('button',{name:'Ver cierre'}));const d=within(screen.getByRole('dialog',{name:'Cierre 2026-07-01 a 2026-09-30'}));expect(d.getByText(/no acredita la presentación de impuestos/)).toBeInTheDocument();expect(d.getByText('Velai de ejemplo')).toBeInTheDocument();expect(d.getByText('Identificador de integridad del cierre')).toBeInTheDocument();});
