import { useState } from 'react';
import { useInfiniteQuery } from '@tanstack/react-query';
import { Link } from 'react-router';
import { api } from '../../api/client';
import { Card, EntityOptions, FormModal, GestionGate, Modal, Money, Notice, opt, str, useGestion, useGuardar, type Catalogos, type Moneda } from './shared';
import { FiscalError, entidadCompleta, incidenciaLabels, type Factura } from './Facturacion';
import './fiscal.css';

interface Ambito {entidad_id:string;moneda:Moneda;desde:string;hasta:string}
interface Totales {base_emitida:number;base_recibida:number;iva_repercutido:number;iva_soportado:number;iva_deducible:number;retenciones_emitidas:number;retenciones_recibidas:number;saldo_iva_provisional:number}
interface ResumenFiscal {ambito:Ambito;totales:Totales;validadas:number;pendientes:number;borradores:number;sin_fecha:number;incidencias:{id:string;codigo:string}[];alcance:string}
interface Cierre extends Ambito {id:string;estado:'cerrado'|'reabierto';version:number;sha256:string;nota:string|null;created_by:string;created_at:string;reabierto_por:string|null;reabierto_en:string|null;motivo_reapertura:string|null;snapshot:ResumenFiscal&{entidad:{nombre:string;nif:string;direccion:string};facturas:Factura[];generado_por:string;generado_en:string}}
export function trimestreActual(now=new Date()){const year=now.getFullYear(),month=Math.floor(now.getMonth()/3)*3;const civil=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return {desde:civil(new Date(year,month,1)),hasta:civil(new Date(year,month+3,0))};}
function Totals({values,moneda}:{values:Totales;moneda:Moneda}){return <div className="fiscal-summary"><Card className="fiscal-primary-stat"><span>Saldo de IVA provisional</span><strong><Money value={values.saldo_iva_provisional} moneda={moneda}/></strong><small>IVA repercutido menos deducción revisada</small></Card><Card><span>IVA repercutido</span><strong><Money value={values.iva_repercutido} moneda={moneda}/></strong><small>Facturas emitidas validadas</small></Card><Card><span>IVA deducible revisado</span><strong><Money value={values.iva_deducible} moneda={moneda}/></strong><small>Facturas recibidas validadas</small></Card></div>;}
function fechaHora(value:string){return new Date(value).toLocaleString('es-ES');}
export function Impuestos(){return <GestionGate><ImpuestosContent/></GestionGate>;}
function ImpuestosContent(){
 const cat=useGestion<Catalogos>('catalogos'),save=useGuardar();const [entidad,setEntidad]=useState(''),[moneda,setMoneda]=useState<Moneda>('EUR');
 const [fechas,setFechas]=useState(()=>trimestreActual()),[closePeriod,setClosePeriod]=useState(false),[selected,setSelected]=useState<Cierre|null>(null),[reopen,setReopen]=useState<Cierre|null>(null);
 const entidadId=entidad||cat.data?.entidades[0]?.id||'';const issuer=cat.data?.entidades.find(e=>e.id===entidadId);
 const rangeError=!fechas.desde||!fechas.hasta?'Selecciona la fecha inicial y final.':fechas.desde>fechas.hasta?'La fecha final debe ser igual o posterior a la inicial.':(Date.parse(fechas.hasta)-Date.parse(fechas.desde))/86400000>366?'Usa un período de hasta 367 días.':'';
 const scope={entidad_id:entidadId,moneda,...fechas};const query=new URLSearchParams(scope).toString();
 const summary=useGestion<ResumenFiscal>(`fiscal/resumen?${query}`,!!entidadId&&!rangeError);const data=summary.data;
 const closuresPath=`cierres?${new URLSearchParams({entidad_id:entidadId,moneda})}`;
 const closures=useInfiniteQuery({queryKey:['gestion',closuresPath],enabled:!!entidadId,initialPageParam:'',queryFn:({pageParam})=>api<{items:Cierre[];nextCursor:string|null}>(`/api/admin/gestion/${closuresPath}${pageParam?`&cursor=${encodeURIComponent(pageParam)}`:''}`),getNextPageParam:last=>last.nextCursor||undefined});
 const rows=closures.data?.pages.flatMap(p=>p.items)||[];
 const incidents=data?.incidencias.reduce<Map<string,string[]>>((all,i)=>{all.set(i.id,[...(all.get(i.id)||[]),incidenciaLabels[i.codigo]||i.codigo]);return all;},new Map())||new Map<string,string[]>();
 return <>
  <div className="fiscal-head"><div><p className="fiscal-eyebrow">ADMINISTRACIÓN · VELAI</p><h1>Impuestos y asesoría</h1><p>Reúne los originales, revisa las cifras y conserva cada cierre.</p></div><Link className="btn alt" to="/facturacion">Ir a facturación</Link></div>
  <Card title="Período de revisión"><div className="fiscal-filters"><label>Emisor<select value={entidadId} onChange={e=>setEntidad(e.target.value)}><option value="">Seleccionar emisor</option>{cat.data?.entidades.map(e=><option value={e.id} key={e.id}>{e.nombre}</option>)}</select></label><label>Moneda<select value={moneda} onChange={e=>setMoneda(e.target.value as Moneda)}><option value="EUR">EUR · euros</option><option value="COP">COP · pesos colombianos</option></select></label><label>Desde<input type="date" value={fechas.desde} max={fechas.hasta||undefined} onChange={e=>setFechas(old=>({...old,desde:e.target.value}))}/></label><label>Hasta<input type="date" value={fechas.hasta} min={fechas.desde||undefined} onChange={e=>setFechas(old=>({...old,hasta:e.target.value}))}/></label></div><div className="g-inline"><button type="button" className="btn alt" onClick={()=>setFechas(trimestreActual())}>Trimestre actual</button><EntityOptions onDone={()=>void cat.refetch()}/></div><FiscalError error={cat.error}/>{rangeError?<p className="g-error" role="alert">{rangeError}</p>:null}{cat.isPending?<p role="status">Cargando emisores…</p>:!issuer?<p className="g-empty">Añade los datos de Velai para organizar sus facturas.</p>:!entidadCompleta(issuer)?<Notice>El emisor todavía está pendiente de configuración fiscal. Puedes preparar los registros; completa y verifica sus datos para validar facturas y cerrar períodos.</Notice>:null}</Card>
  <FiscalError error={summary.error}/>{entidadId&&!rangeError&&summary.isPending?<p role="status">Calculando el resumen del período…</p>:null}
  {data&&!rangeError?<>
   <Totals values={data.totales} moneda={moneda}/>
   <p className="fiscal-scope-note">Solo se suman versiones vigentes y validadas. El período usa la fecha de operación o, si falta, la de expedición. Este saldo orientativo no es la cuota del modelo 303 y no incluye otros impuestos, compensaciones o regímenes especiales.</p>
   <div className="fiscal-status-strip" aria-label="Estado de los registros"><span><strong>{data.validadas}</strong> validadas</span><span><strong>{data.pendientes}</strong> pendientes de revisión</span><span><strong>{data.borradores}</strong> borradores</span><span><strong>{data.sin_fecha}</strong> sin fecha asignable</span></div>
   <Card title="Detalle del libro interno"><dl className="fiscal-detail-grid"><div><dt>Bases de facturas emitidas</dt><dd><Money value={data.totales.base_emitida} moneda={moneda}/></dd></div><div><dt>Bases de facturas recibidas</dt><dd><Money value={data.totales.base_recibida} moneda={moneda}/></dd></div><div><dt>IVA soportado registrado</dt><dd><Money value={data.totales.iva_soportado} moneda={moneda}/></dd></div><div><dt>Retenciones en emitidas</dt><dd><Money value={data.totales.retenciones_emitidas} moneda={moneda}/></dd></div><div><dt>Retenciones en recibidas</dt><dd><Money value={data.totales.retenciones_recibidas} moneda={moneda}/></dd></div></dl></Card>
   <Card title="Pendientes antes del cierre" action={<Link to="/facturacion">Revisar facturas</Link>}>
    {incidents.size?<ul className="fiscal-incidents">{[...incidents].map(([id,issues],i)=><li key={id}><div><strong>Registro con incidencias {i+1}</strong><p>{issues.join(' · ')}</p></div><Link to={`/facturacion?factura=${encodeURIComponent(id)}`}>Abrir registro</Link></li>)}</ul>:<p className="g-empty">No hay incidencias detectadas en los registros de este período.</p>}
    {data.sin_fecha>0?<Notice>Hay {data.sin_fecha} registro(s) sin fecha de este emisor y moneda. No se pueden asignar al período; completa la fecha desde Facturación antes de cerrar o conserva expresamente esa incidencia.</Notice>:null}
   </Card>
   <Card title="Preparar para asesoría"><p>Descarga las líneas del libro y sus incidencias. La asesoría revisa su clasificación y las obligaciones que correspondan.</p><div className="g-inline"><a className="btn alt" href={`/api/admin/gestion/fiscal/export.csv?${query}`}>Descargar CSV para asesoría</a><button type="button" className="btn" disabled={!entidadCompleta(issuer)||summary.isFetching} onClick={()=>setClosePeriod(true)}>Cerrar período interno</button></div><Notice>El CSV es una exportación interna. Descargarlo o cerrar el período no presenta una declaración ni paga impuestos.</Notice></Card>
  </>:null}
  <Card title="Historial de cierres"><FiscalError error={closures.error}/>{entidadId&&closures.isPending?<p role="status">Cargando cierres…</p>:rows.length?<div className="g-table"><table><caption className="fiscal-sr-only">Cierres internos del emisor y moneda seleccionados</caption><thead><tr><th>Período</th><th>Estado</th><th>Creado</th><th>Registros</th><th>Acciones</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.desde} → {c.hasta}<small>{c.moneda}</small></td><td><span className={`fiscal-tag ${c.estado==='cerrado'?'is-valid':''}`}>{c.estado==='cerrado'?'Cerrado':'Reabierto'}</span></td><td>{fechaHora(c.created_at)}<small>{c.created_by}</small></td><td>{c.snapshot.validadas} validadas<small>{c.snapshot.pendientes+c.snapshot.borradores} pendientes / borradores</small></td><td><div className="g-inline"><button type="button" className="btn alt" onClick={()=>setSelected(c)}>Ver cierre</button>{c.estado==='cerrado'?<button type="button" className="btn alt" onClick={()=>setReopen(c)}>Reabrir</button>:null}</div></td></tr>)}</tbody></table></div>:<p className="g-empty">Todavía no hay cierres. El historial conservará las cifras y los documentos revisados en cada uno.</p>}{closures.hasNextPage?<button type="button" className="btn alt" disabled={closures.isFetchingNextPage} onClick={()=>void closures.fetchNextPage()}>{closures.isFetchingNextPage?'Cargando…':'Cargar más cierres'}</button>:null}</Card>
  <div className="fiscal-bottom"><a href="https://sede.agenciatributaria.gob.es/Sede/iva/facturacion-registro/facturacion-iva/obligacion-conservar-facturas.html" target="_blank" rel="noreferrer">AEAT · conservación de facturas ↗</a><a href="https://sede.agenciatributaria.gob.es/Sede/calendario-contribuyente.html" target="_blank" rel="noreferrer">AEAT · calendario del contribuyente ↗</a></div>
  {closePeriod&&data?<FormModal title="Cerrar período interno" close={()=>setClosePeriod(false)} label="Confirmar cierre interno" fields={[{name:'nota',label:'Nota para el cierre (opcional)',type:'textarea'}]} submit={(d,id)=>save.mutateAsync({path:'cierres',body:{id,...scope,nota:opt(d,'nota'),aceptar_pendientes:d.get('aceptar_pendientes')==='on'}})}><Notice>Se conservarán las versiones actuales, sus originales y las cifras de {fechas.desde} a {fechas.hasta}. Para modificarlas después tendrás que reabrir el período con un motivo.</Notice>{data.incidencias.length||data.sin_fecha?<label className="fiscal-checkbox"><input name="aceptar_pendientes" type="checkbox" required/>He revisado los {incidents.size} registros con incidencias y los {data.sin_fecha} sin fecha. Acepto conservarlos como pendientes, sin sumarlos como deducibles.</label>:null}</FormModal>:null}
  {reopen?<FormModal title="Reabrir período interno" close={()=>setReopen(null)} label="Reabrir con motivo" fields={[{name:'motivo',label:'Motivo de la reapertura',type:'textarea',required:true,help:'Describe el motivo con al menos cinco caracteres.'}]} submit={d=>{const motivo=str(d,'motivo');if(motivo.length<5)throw new Error('motivo_insuficiente');return save.mutateAsync({path:`cierres/${reopen.id}/reabrir`,body:{version:reopen.version,motivo}});}}><Notice>Se conserva el cierre original. Reabrir permite corregir el libro interno; no modifica una declaración que se haya presentado fuera de Velai.</Notice></FormModal>:null}
  {selected?<ClosureDetail item={selected} close={()=>setSelected(null)}/>:null}
 </>;
}
function ClosureDetail({item,close}:{item:Cierre;close:()=>void}){
 const [shown,setShown]=useState(30);const s=item.snapshot;
 return <Modal title={`Cierre ${item.desde} a ${item.hasta}`} close={close}><div className="fiscal-detail-top"><span className="fiscal-tag">{item.estado==='cerrado'?'Cerrado':'Reabierto'}</span><strong>{s.entidad.nombre}</strong><span>NIF: {s.entidad.nif}</span></div><p>{s.entidad.direccion}</p><p>Conservado el {fechaHora(item.created_at)} por {item.created_by}.</p>{item.nota?<p>{item.nota}</p>:null}<Totals values={s.totales} moneda={item.moneda}/><p>{s.validadas} registros validados · {s.pendientes} pendientes · {s.borradores} borradores · {s.sin_fecha||0} sin fecha</p>{item.estado==='reabierto'?<Notice>Reabierto el {item.reabierto_en?fechaHora(item.reabierto_en):'—'} por {item.reabierto_por}. Motivo: {item.motivo_reapertura}</Notice>:null}<Card title="Registros conservados">{s.facturas.length?<div className="g-table"><table><thead><tr><th>Documento</th><th>Contraparte</th><th>Estado al cerrar</th><th>Importe registrado</th></tr></thead><tbody>{s.facturas.slice(0,shown).map(f=><tr key={f.id}><td><Link to={`/facturacion?factura=${encodeURIComponent(f.id)}`}>{f.numero||'Borrador sin número'}</Link></td><td>{f.contraparte_nombre||'Pendiente'}</td><td>{f.estado==='validada'?'Validada':f.estado==='borrador'?'Borrador':'Pendiente de revisión'}</td><td><Money value={f.total} moneda={item.moneda}/></td></tr>)}</tbody></table></div>:<p>No había facturas fechadas en este rango.</p>}{shown<s.facturas.length?<button type="button" className="btn alt" onClick={()=>setShown(n=>n+30)}>Mostrar más registros del cierre</button>:null}</Card>{s.incidencias.length?<div className="fiscal-pending"><strong>Incidencias conservadas</strong><ul>{s.incidencias.map((v,i)=><li key={`${v.id}-${v.codigo}-${i}`}>{incidenciaLabels[v.codigo]||v.codigo} · <Link to={`/facturacion?factura=${encodeURIComponent(v.id)}`}>Abrir registro</Link></li>)}</ul></div>:null}<details className="fiscal-integrity"><summary>Identificador de integridad del cierre</summary><code>{item.sha256}</code><p>Permite comparar esta copia con la información que se conservó al cerrar.</p></details><Notice>Estas cifras son las del momento del cierre. Las incidencias se conservan como tales; este documento no acredita la presentación de impuestos.</Notice></Modal>;
}
