export const ADMIN_HTML = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>Leads · Velai</title>
<style nonce="__NONCE__">
:root{color-scheme:dark;--bg:#0c0d10;--panel:#17191f;--line:#2b2e37;--muted:#9298a8;--orange:#ff6b1a;--ok:#46d18c;--bad:#ff6b6b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f7f7f8;font:14px system-ui,sans-serif}button,input,select,textarea{font:inherit}header{padding:22px max(20px,4vw);display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line)}h1{margin:0;font-size:22px}main{padding:24px max(20px,4vw)}.filters{display:grid;grid-template-columns:2fr repeat(6,1fr) auto;gap:10px;margin-bottom:18px}.filters input,.filters select,.note textarea{width:100%;background:var(--panel);color:#fff;border:1px solid var(--line);border-radius:9px;padding:10px}.btn{border:0;border-radius:9px;padding:10px 14px;background:var(--orange);color:#fff;cursor:pointer;font-weight:700}.btn.alt{background:#292d37}.btn.bad{background:#8d3030}.table{border:1px solid var(--line);border-radius:12px;overflow:auto;background:var(--panel)}table{width:100%;border-collapse:collapse;min-width:920px}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--line)}th{color:var(--muted);font-size:12px}tr[data-id]{cursor:pointer}tr[data-id]:hover{background:#20232b}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 8px}.muted{color:var(--muted)}.pager{text-align:center;margin:18px}.empty{text-align:center;padding:36px;color:var(--muted)}dialog{width:min(760px,calc(100% - 24px));max-height:90vh;overflow:auto;background:var(--panel);color:#fff;border:1px solid var(--line);border-radius:14px;padding:0}dialog::backdrop{background:#000b}.modal-h{position:sticky;top:0;background:var(--panel);display:flex;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--line)}.modal-b{padding:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{background:#111319;border:1px solid var(--line);border-radius:10px;padding:12px}.card b{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;margin-bottom:5px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.note{display:flex;gap:8px}.timeline{margin-top:20px}.timeline article{border-left:2px solid var(--line);padding:0 0 14px 12px}.error{color:var(--bad)}@media(max-width:850px){.filters{grid-template-columns:1fr 1fr}.filters input{grid-column:1/-1}.grid{grid-template-columns:1fr}}
</style></head><body>
<header><h1>Velai · Leads</h1><button class="btn alt" id="export">Exportar CSV</button></header>
<main><form class="filters" id="filters"><input name="q" placeholder="Buscar nombre, teléfono, sector…"><select name="tenant" id="tenantFilter"><option value="">Todos los clientes</option></select><select name="status"><option value="">Todos los estados</option><option>new</option><option>contacted</option><option>qualified</option><option>won</option><option>lost</option><option>spam</option></select><select name="notification"><option value="">Todos los avisos</option><option>pending</option><option>sent</option><option>failed</option><option>skipped</option></select><input name="source" placeholder="Fuente"><input name="from" type="date"><input name="to" type="date"><button class="btn">Filtrar</button></form>
<div id="message"></div><div class="table"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Estado</th><th>Nombre</th><th>WhatsApp</th><th>Sector</th><th>Fuente</th><th>Avisos</th></tr></thead><tbody id="rows"></tbody></table></div><div class="pager"><button class="btn alt" id="more" hidden>Cargar más</button></div></main>
<dialog id="detail"><div class="modal-h"><strong>Detalle del lead</strong><button class="btn alt" id="close">Cerrar</button></div><div class="modal-b" id="detailBody"></div></dialog>
<script nonce="__NONCE__">
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cursor=null,current=null;
function params(){const p=new URLSearchParams(new FormData($('#filters')));for(const[k,v]of[...p])if(!v)p.delete(k);return p}
async function api(path,options){const r=await fetch(path,options);if(r.status===204)return null;const d=await r.json();if(!r.ok)throw Error(d.error||'request_failed');return d}
function fmt(v){return v?new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'}
async function load(append=false){try{const p=params();if(append&&cursor)p.set('cursor',cursor);const d=await api('/api/admin/leads?'+p);if(!append)$('#rows').innerHTML='';if(!d.leads.length&&!append)$('#rows').innerHTML='<tr><td colspan="8" class="empty">No hay leads con estos filtros.</td></tr>';for(const l of d.leads)$('#rows').insertAdjacentHTML('beforeend','<tr data-id="'+l.id+'"><td>'+fmt(l.created_at)+'</td><td>'+esc(l.tenant_name||'—')+'</td><td><span class="pill">'+esc(l.status)+'</span></td><td>'+esc(l.name||'—')+'</td><td>'+esc(l.whatsapp||'—')+'</td><td>'+esc(l.sector||'—')+'</td><td>'+esc(l.source)+'</td><td class="muted">'+esc(l.notification_summary||'—')+'</td></tr>');cursor=d.nextCursor;$('#more').hidden=!cursor;$('#message').textContent=''}catch(e){$('#message').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function loadTenants(){try{const d=await api('/api/admin/tenants');for(const t of d.tenants)$('#tenantFilter').insertAdjacentHTML('beforeend','<option value="'+esc(t.id)+'">'+esc(t.name)+'</option>')}catch(e){/* sin tenants: el filtro queda en Todos */}}
$('#filters').onsubmit=e=>{e.preventDefault();cursor=null;load()};$('#more').onclick=()=>load(true);$('#export').onclick=()=>location.href='/api/admin/leads/export.csv?'+params();$('#close').onclick=()=>$('#detail').close();
$('#rows').onclick=e=>{const tr=e.target.closest('[data-id]');if(tr)openLead(tr.dataset.id)};
async function openLead(id){try{const d=await api('/api/admin/leads/'+id);current=d.lead;const l=d.lead;const cards=[['Fecha',fmt(l.created_at)],['Cliente',l.tenant_name],['Nombre',l.name],['WhatsApp',l.whatsapp],['Sector',l.sector],['Fuente',l.source],['Mensajes/día',l.messages_per_day],['Canal',l.channel],['Puntuación',l.score],['Nota',l.note],['Página',l.page_url]].map(x=>'<div class="card"><b>'+x[0]+'</b>'+esc(x[1]??'—')+'</div>').join('');const options=['new','contacted','qualified','won','lost','spam'].map(s=>'<option '+(s===l.status?'selected':'')+'>'+s+'</option>').join('');const notices=d.notifications.map(n=>'<article><b>Aviso '+esc(n.channel)+': '+esc(n.status)+'</b><div class="muted">Intentos: '+n.attempts+(n.last_error?' · '+esc(n.last_error):'')+'</div></article>').join('');const notes=d.notes.map(n=>'<article><b>'+esc(n.author_email)+'</b><div>'+esc(n.text)+'</div><small class="muted">'+fmt(n.created_at)+'</small></article>').join('');const events=d.events.map(n=>'<article><b>'+esc(n.event_type)+'</b><div>'+esc(n.detail||'')+'</div><small class="muted">'+fmt(n.created_at)+' · '+esc(n.actor_email)+'</small></article>').join('');$('#detailBody').innerHTML='<div class="grid">'+cards+'</div><div class="actions"><select id="status">'+options+'</select><button class="btn" id="saveStatus">Guardar estado</button><button class="btn alt" id="retry">Reintentar avisos</button><button class="btn bad" id="delete">Borrar lead</button></div><div class="note"><textarea id="note" rows="3" placeholder="Añadir nota…"></textarea><button class="btn" id="addNote">Añadir</button></div><div class="timeline"><h3>Actividad</h3>'+notices+notes+events+'</div>';wireDetail();$('#detail').showModal()}catch(e){alert(e.message)}}
function wireDetail(){$('#saveStatus').onclick=async()=>{await api('/api/admin/leads/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:$('#status').value})});$('#detail').close();load()};$('#retry').onclick=async()=>{await api('/api/admin/leads/'+current.id+'/retry',{method:'POST'});openLead(current.id)};$('#addNote').onclick=async()=>{const text=$('#note').value.trim();if(!text)return;await api('/api/admin/leads/'+current.id+'/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});openLead(current.id)};$('#delete').onclick=async()=>{if(!confirm('¿Borrar definitivamente este lead y todos sus datos?'))return;await api('/api/admin/leads/'+current.id,{method:'DELETE'});$('#detail').close();load()}}
loadTenants();load();
</script></body></html>`;

export const ADMIN_HEADERS = {
  'Content-Type': 'text/html; charset=utf-8',
  'Cache-Control': 'no-store',
  'X-Robots-Tag': 'noindex, nofollow',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'no-referrer',
};
